EXTENDED_DD_RULES = [
    # ── 循環器 ──────────────────────────────────────────────────
    {
        "id": "ACS",
        "keywords": ["前胸部", "胸痛", "圧迫感", "放散痛", "ST上昇", "冷汗", "絞扼感"],
        "diagnoses": [
            {"disease": "急性冠症候群（ACS）",    "icd10": "I21.9", "base_prob": 0.68, "boost_kw": ["ST上昇","TnI","心電図","糖尿病","高血圧","喫煙"]},
            {"disease": "大動脈解離",             "icd10": "I71.0", "base_prob": 0.14, "boost_kw": ["引き裂く","血圧左右差","背部痛","マルファン"]},
            {"disease": "肺塞栓症",               "icd10": "I26.9", "base_prob": 0.10, "boost_kw": ["下肢浮腫","旅行歴","術後","Wells","D-dimer"]},
            {"disease": "急性心膜炎",             "icd10": "I30.9", "base_prob": 0.05, "boost_kw": ["体位","摩擦音","前傾位","SR上昇"]},
            {"disease": "食道痙攣",               "icd10": "K22.4", "base_prob": 0.03, "boost_kw": ["嚥下時","ニトロ有効","内視鏡"]},
        ],
        "red_flags": ["12誘導心電図即時確認", "TnI採血", "循環器緊急コール"],
        "next_steps": ["12誘導心電図", "採血(TnI/CK-MB/BNP)", "胸部X線", "心エコー"],
        "scoring_hints": ["HEART score算出を推奨"],
        "urgency_override": "immediate",
    },
    {
        "id": "AHF",
        "keywords": ["起座呼吸", "両下腿浮腫", "心不全", "BNP", "浮腫", "体重増加"],
        "diagnoses": [
            {"disease": "急性心不全（代償不全）",  "icd10": "I50.9", "base_prob": 0.72, "boost_kw": ["起座呼吸","心筋梗塞既往","BNP","両下腿浮腫"]},
            {"disease": "肺塞栓症",               "icd10": "I26.9", "base_prob": 0.12, "boost_kw": ["突然発症","片側浮腫","胸膜性胸痛"]},
            {"disease": "COPD増悪",               "icd10": "J44.1", "base_prob": 0.09, "boost_kw": ["喫煙歴","慢性咳嗽","過膨張"]},
            {"disease": "肺炎",                   "icd10": "J18.9", "base_prob": 0.07, "boost_kw": ["発熱","片側浸潤","CRP上昇"]},
        ],
        "red_flags": ["SpO2 90%以下は即時酸素投与", "起座呼吸は重篤な肺うっ血"],
        "next_steps": ["胸部X線(バット翼陰影)", "BNP/NT-proBNP", "心エコー", "ニトログリセリン+フロセミド"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    {
        "id": "AORTA",
        "keywords": ["大動脈", "引き裂く", "血圧左右差", "縦隔拡大", "解離"],
        "diagnoses": [
            {"disease": "急性大動脈解離",         "icd10": "I71.0", "base_prob": 0.78, "boost_kw": ["引き裂く","血圧左右差","マルファン","高血圧","突然"]},
            {"disease": "急性冠症候群（ACS）",    "icd10": "I21.9", "base_prob": 0.12, "boost_kw": ["ST変化","TnI","喫煙"]},
            {"disease": "大動脈瘤破裂",           "icd10": "I71.3", "base_prob": 0.10, "boost_kw": ["ショック","腹部拍動性腫瘤"]},
        ],
        "red_flags": ["造影CT緊急施行", "外科緊急コール", "血圧両側測定"],
        "next_steps": ["造影CT胸腹部", "外科コンサルト", "血圧両側測定+HR管理"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    # ── 神経 ────────────────────────────────────────────────────
    {
        "id": "SAH",
        "keywords": ["雷鳴頭痛", "thunderclap", "項部硬直", "羞明", "突然の激頭痛"],
        "diagnoses": [
            {"disease": "くも膜下出血（SAH）",    "icd10": "I60.9", "base_prob": 0.72, "boost_kw": ["雷鳴","突然","最悪","項部硬直","嘔吐"]},
            {"disease": "細菌性髄膜炎",           "icd10": "G00.9", "base_prob": 0.14, "boost_kw": ["発熱","意識","皮疹","点状出血"]},
            {"disease": "脳内出血",               "icd10": "I61.9", "base_prob": 0.08, "boost_kw": ["高血圧","抗凝固薬","局所神経"]},
            {"disease": "偏頭痛",                 "icd10": "G43.9", "base_prob": 0.06, "boost_kw": ["既往","前兆","若年","女性","光過敏"]},
        ],
        "red_flags": ["CT陰性でもLP必須(キサントクロミア)", "SAH否定まで緊急扱い"],
        "next_steps": ["頭部単純CT", "LP(CT陰性時)", "脳外科コール"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    {
        "id": "STROKE",
        "keywords": ["片麻痺", "構音障害", "顔面神経麻痺", "失語", "NIHSS", "脳卒中"],
        "diagnoses": [
            {"disease": "急性脳梗塞",             "icd10": "I63.9", "base_prob": 0.73, "boost_kw": ["心房細動","突然発症","片麻痺","失語"]},
            {"disease": "脳内出血",               "icd10": "I61.9", "base_prob": 0.16, "boost_kw": ["抗凝固薬","高血圧","頭痛","嘔吐"]},
            {"disease": "TIA",                    "icd10": "G45.9", "base_prob": 0.07, "boost_kw": ["症状消失","短時間","一過性"]},
            {"disease": "Todd麻痺",               "icd10": "G83.8", "base_prob": 0.04, "boost_kw": ["けいれん後","一過性","消失傾向"]},
        ],
        "red_flags": ["発症時刻確認必須(tPA適応判断)", "NIHSS評価"],
        "next_steps": ["頭部CT(出血除外)", "NIHSS評価", "脳卒中チーム緊急コール", "発症時刻確認"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    {
        "id": "MENINGITIS",
        "keywords": ["発熱", "頸部硬直", "髄膜", "Kernig", "点状出血", "項部"],
        "diagnoses": [
            {"disease": "細菌性髄膜炎",           "icd10": "G00.9", "base_prob": 0.73, "boost_kw": ["頸部硬直","点状出血","意識障害","若年","発熱"]},
            {"disease": "ウイルス性髄膜炎",       "icd10": "A87.9", "base_prob": 0.15, "boost_kw": ["比較的軽症","頭痛","嘔吐","発熱"]},
            {"disease": "ウイルス性脳炎（ヘルペス）", "icd10": "B00.4", "base_prob": 0.08, "boost_kw": ["局所神経","側頭葉","精神症状"]},
            {"disease": "くも膜下出血",           "icd10": "I60.9", "base_prob": 0.04, "boost_kw": ["雷鳴頭痛","突然"]},
        ],
        "red_flags": ["抗菌薬を30分以内に投与", "点状出血はDIC/Waterhouse-Friderichsen"],
        "next_steps": ["血培2セット採取→即セフトリアキソン2g", "デキサメサゾン（抗菌薬前）", "ICU管理"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    {
        "id": "SEIZURE",
        "keywords": ["けいれん", "てんかん", "発作", "意識消失", "痙攣"],
        "diagnoses": [
            {"disease": "てんかん重積状態（SE）",  "icd10": "G41.9", "base_prob": 0.55, "boost_kw": ["5分以上","繰り返し","意識回復なし"]},
            {"disease": "症候性てんかん（脳炎）", "icd10": "G40.9", "base_prob": 0.15, "boost_kw": ["発熱","頭痛","意識障害"]},
            {"disease": "低血糖発作",             "icd10": "E16.0", "base_prob": 0.12, "boost_kw": ["糖尿病","インスリン","血糖低値"]},
            {"disease": "電解質異常（低Na）",     "icd10": "E87.1", "base_prob": 0.10, "boost_kw": ["低Na","低Mg","低Ca"]},
            {"disease": "子癇発作",               "icd10": "O15.9", "base_prob": 0.08, "boost_kw": ["妊婦","妊娠","高血圧"]},
        ],
        "red_flags": ["5分以上持続→ジアゼパム/ミダゾラム即投与", "気道確保"],
        "next_steps": ["BZD投与(ジアゼパム5-10mg)", "血糖測定", "頭部CT", "EEG"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    # ── 呼吸器 ──────────────────────────────────────────────────
    {
        "id": "CAP",
        "keywords": ["発熱", "湿性咳嗽", "打診濁音", "浸潤影", "肺炎", "CRP上昇"],
        "diagnoses": [
            {"disease": "市中肺炎（CAP）",        "icd10": "J18.9", "base_prob": 0.70, "boost_kw": ["湿性咳","打診濁音","CRP","肺炎球菌"]},
            {"disease": "肺結核",                 "icd10": "A15.9", "base_prob": 0.12, "boost_kw": ["渡航歴","夜間発汗","体重減少","上葉","空洞"]},
            {"disease": "非定型肺炎",             "icd10": "J22",   "base_prob": 0.10, "boost_kw": ["乾性咳","若年","β-ラクタム無効","マイコプラズマ"]},
            {"disease": "肺癌+閉塞性肺炎",       "icd10": "C34.9", "base_prob": 0.05, "boost_kw": ["喫煙歴","繰り返す","高齢","血痰"]},
            {"disease": "好酸球性肺炎",           "icd10": "J82",   "base_prob": 0.03, "boost_kw": ["好酸球増加","抗菌薬無効","ステロイド反応"]},
        ],
        "red_flags": ["CURB-65スコアで入院適応判定", "結核疑いは陰圧個室+N95"],
        "next_steps": ["胸部X線", "採血(CBC/CRP/PCT)", "喀痰培養", "CURB-65算定"],
        "scoring_hints": ["CURB-65", "PSI/PORT"],
        "urgency_override": None,
    },
    {
        "id": "PE",
        "keywords": ["肺塞栓", "DVT", "D-dimer", "Wells", "突然の呼吸困難", "胸膜性胸痛"],
        "diagnoses": [
            {"disease": "肺塞栓症（PE）",         "icd10": "I26.9", "base_prob": 0.72, "boost_kw": ["片側浮腫","旅行歴","術後","Wells","D-dimer上昇"]},
            {"disease": "急性冠症候群",           "icd10": "I21.9", "base_prob": 0.12, "boost_kw": ["ST変化","TnI","喫煙"]},
            {"disease": "気胸",                   "icd10": "J93.9", "base_prob": 0.08, "boost_kw": ["若年","やせ形","患側呼吸音消失","叩打音"]},
            {"disease": "胸膜炎",                 "icd10": "R09.1", "base_prob": 0.08, "boost_kw": ["体位依存","胸膜摩擦音","発熱"]},
        ],
        "red_flags": ["Wellsスコア+D-dimer評価", "CTPA（CT肺動脈造影）"],
        "next_steps": ["Wells score算出", "D-dimer", "CTPA", "抗凝固療法開始"],
        "scoring_hints": ["Wells PE score"],
        "urgency_override": None,
    },
    {
        "id": "COPD",
        "keywords": ["COPD", "慢性閉塞性", "喘鳴", "慢性咳嗽", "SpO2低下", "呼吸困難"],
        "diagnoses": [
            {"disease": "COPD急性増悪",           "icd10": "J44.1", "base_prob": 0.65, "boost_kw": ["喫煙歴","慢性咳嗽","たるぼ型","呼気延長"]},
            {"disease": "気管支喘息発作",         "icd10": "J45.9", "base_prob": 0.18, "boost_kw": ["アレルギー歴","夜間","β2作動薬有効"]},
            {"disease": "心不全",                 "icd10": "I50.9", "base_prob": 0.12, "boost_kw": ["浮腫","BNP","起座呼吸"]},
            {"disease": "肺炎",                   "icd10": "J18.9", "base_prob": 0.05, "boost_kw": ["発熱","CRP上昇","浸潤影"]},
        ],
        "red_flags": ["pH<7.35→NIV/挿管", "PaCO2上昇は呼吸性アシドーシス"],
        "next_steps": ["酸素投与(目標SpO2 88-92%)", "気管支拡張薬吸入", "全身ステロイド", "血液ガス"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    {
        "id": "PNEUMOTHORAX",
        "keywords": ["気胸", "胸痛", "患側呼吸音消失", "叩打音", "やせ型"],
        "diagnoses": [
            {"disease": "自然気胸",               "icd10": "J93.1", "base_prob": 0.72, "boost_kw": ["若年","やせ形","突然","患側消失"]},
            {"disease": "緊張性気胸",             "icd10": "J93.0", "base_prob": 0.15, "boost_kw": ["ショック","縦隔偏位","頸静脈怒張","外傷"]},
            {"disease": "血胸",                   "icd10": "J94.2", "base_prob": 0.08, "boost_kw": ["外傷","鈍的","貫通"]},
            {"disease": "肺塞栓症",               "icd10": "I26.9", "base_prob": 0.05, "boost_kw": ["D-dimer","浮腫","旅行"]},
        ],
        "red_flags": ["緊張性気胸は即刻胸腔穿刺（診断的兼治療的）"],
        "next_steps": ["胸部X線", "胸腔穿刺/ドレナージ（緊張性）", "呼吸器科コール"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    # ── 消化器 ──────────────────────────────────────────────────
    {
        "id": "APPENDICITIS",
        "keywords": ["右下腹部", "McBurney", "虫垂", "反跳痛", "Rovsing"],
        "diagnoses": [
            {"disease": "急性虫垂炎",             "icd10": "K37",   "base_prob": 0.65, "boost_kw": ["McBurney","反跳痛","WBC上昇","CRP上昇","CT"]},
            {"disease": "卵巣捻転",               "icd10": "N83.5", "base_prob": 0.12, "boost_kw": ["女性","骨盤痛","間歇性","超音波"]},
            {"disease": "異所性妊娠",             "icd10": "O00.9", "base_prob": 0.10, "boost_kw": ["女性","月経遅延","β-hCG","妊娠"]},
            {"disease": "右卵巣嚢腫破裂",         "icd10": "N83.1", "base_prob": 0.08, "boost_kw": ["突然","激痛","女性","腹水"]},
            {"disease": "腸管膜リンパ節炎",       "icd10": "I88.0", "base_prob": 0.05, "boost_kw": ["上気道炎先行","小児","若年"]},
        ],
        "red_flags": ["女性は必ず尿妊娠反応（β-hCG）確認", "穿孔後は汎発性腹膜炎"],
        "next_steps": ["尿妊娠反応（女性）", "腹部超音波", "腹部CT", "外科コンサルト"],
        "scoring_hints": ["Alvarado score", "AIR score"],
        "urgency_override": None,
    },
    {
        "id": "CHOLANGITIS",
        "keywords": ["黄疸", "胆管", "Charcot", "胆石", "Murphy", "季肋部"],
        "diagnoses": [
            {"disease": "急性胆管炎",             "icd10": "K83.0", "base_prob": 0.62, "boost_kw": ["黄疸","Charcot","胆石","胆管拡張","発熱"]},
            {"disease": "急性胆嚢炎",             "icd10": "K81.0", "base_prob": 0.20, "boost_kw": ["Murphy陽性","壁肥厚","黄疸なし"]},
            {"disease": "急性膵炎",               "icd10": "K85.9", "base_prob": 0.12, "boost_kw": ["アミラーゼ","リパーゼ","背部放散痛","飲酒"]},
            {"disease": "肝膿瘍",                 "icd10": "K75.0", "base_prob": 0.06, "boost_kw": ["アメーバ","海外","CTで低吸収"]},
        ],
        "red_flags": ["Charcot三徴=胆管炎", "Reynolds五徴（+ショック+意識障害）は重症"],
        "next_steps": ["腹部超音波", "採血(肝機能/GGT/ALP/培養)", "抗菌薬", "緊急ERCP/PTCD"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    {
        "id": "PANCREATITIS",
        "keywords": ["膵炎", "アミラーゼ", "リパーゼ", "心窩部", "背部放散痛", "飲酒"],
        "diagnoses": [
            {"disease": "急性膵炎",               "icd10": "K85.9", "base_prob": 0.78, "boost_kw": ["アミラーゼ","リパーゼ","飲酒","胆石","CT"]},
            {"disease": "消化性潰瘍穿孔",         "icd10": "K27.1", "base_prob": 0.10, "boost_kw": ["突然","腹部全体","腹膜刺激","free air"]},
            {"disease": "SMA閉塞",                "icd10": "K55.0", "base_prob": 0.07, "boost_kw": ["突然","pain out of proportion","心房細動"]},
            {"disease": "急性胆嚢炎",             "icd10": "K81.0", "base_prob": 0.05, "boost_kw": ["Murphy","季肋部","超音波"]},
        ],
        "red_flags": ["Ranson基準/BISAPスコアで重症度評価", "SMA閉塞は死亡率80%以上"],
        "next_steps": ["採血(アミラーゼ/リパーゼ/CRP)", "腹部CT(造影)", "禁食+輸液", "Ranson評価"],
        "scoring_hints": ["Ranson criteria", "BISAP score"],
        "urgency_override": None,
    },
    {
        "id": "GI_BLEED",
        "keywords": ["吐血", "下血", "タール便", "血便", "消化管出血", "Hb低下", "失血", "黒色便", "血性"],
        "diagnoses": [
            {"disease": "消化性潰瘍出血（上部GI）","icd10":"K27.4","base_prob": 0.50,"boost_kw": ["吐血","NSAID","H.pylori","コーヒー残渣様"]},
            {"disease": "大腸出血（下部GI）",      "icd10": "K92.1","base_prob": 0.25,"boost_kw": ["鮮血便","大腸憩室","大腸癌","直腸癌"]},
            {"disease": "食道静脈瘤破裂",          "icd10": "I85.0","base_prob": 0.15,"boost_kw": ["肝硬変","アルコール","大量吐血"]},
            {"disease": "Mallory-Weiss症候群",     "icd10": "K22.6","base_prob": 0.10,"boost_kw": ["嘔吐後","アルコール","少量"]},
        ],
        "red_flags": ["大量吐血はショック管理優先", "肝硬変既往は食道静脈瘤を第一に"],
        "next_steps": ["大口径ルート2本確保", "輸血(Hb<7g/dL)", "消化器内視鏡緊急", "消化器コール"],
        "scoring_hints": ["Blatchford score（上部GI）", "Glasgow-Blatchford score"],
        "urgency_override": None,
    },
    # ── 内分泌・代謝 ────────────────────────────────────────────
    {
        "id": "DKA",
        "keywords": ["クスマウル", "DKA", "ケトン", "血糖", "糖尿", "意識障害", "代謝性アシドーシス"],
        "diagnoses": [
            {"disease": "糖尿病性ケトアシドーシス（DKA）","icd10":"E10.1","base_prob": 0.78,"boost_kw": ["1型","インスリン中断","クスマウル","ケトン","pH<7.3"]},
            {"disease": "高血糖高浸透圧症候群（HHS）","icd10":"E11.0","base_prob": 0.10,"boost_kw": ["2型","血糖>600","ケトーシス軽度"]},
            {"disease": "乳酸アシドーシス",         "icd10": "E87.2","base_prob": 0.07,"boost_kw": ["ビグアナイド","腎不全","ショック","乳酸>4"]},
            {"disease": "アルコール性ケトアシドーシス","icd10":"E87.2","base_prob": 0.05,"boost_kw": ["飲酒","血糖正常〜低値","嘔吐"]},
        ],
        "red_flags": ["クスマウル呼吸=重篤なアシドーシス", "K値モニタリング必須（インスリン投与前）"],
        "next_steps": ["血糖/ガス/電解質/ケトン", "輸液(NS 1L/h)", "インスリン持続", "K補充"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    {
        "id": "HYPOGLYCEMIA",
        "keywords": ["低血糖", "冷汗", "振戦", "動悸", "血糖低下"],
        "diagnoses": [
            {"disease": "薬剤性低血糖（SU/インスリン）","icd10":"E16.0","base_prob": 0.72,"boost_kw": ["インスリン","スルホニル尿素","糖尿病"]},
            {"disease": "インスリノーマ",           "icd10": "D13.7","base_prob": 0.10,"boost_kw": ["反復性","空腹時","Whipple三徴"]},
            {"disease": "副腎不全",                 "icd10": "E27.4","base_prob": 0.10,"boost_kw": ["副腎","ステロイド中断","色素沈着","低Na"]},
            {"disease": "劇症1型糖尿病",            "icd10": "E10.9","base_prob": 0.08,"boost_kw": ["急激発症","flu様","ケトーシス軽度"]},
        ],
        "red_flags": ["血糖<50mg/dL→即座に補糖", "SU剤による低血糖は遷延→入院"],
        "next_steps": ["血糖測定", "50%ブドウ糖20-40mL静注（意識障害時）", "原因薬剤確認"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    {
        "id": "THYROID_CRISIS",
        "keywords": ["甲状腺クリーゼ", "甲状腺", "頻脈", "高体温", "眼球突出", "Burch-Wartofsky"],
        "diagnoses": [
            {"disease": "甲状腺クリーゼ",          "icd10": "E05.5","base_prob": 0.70,"boost_kw": ["頻脈","高体温","心不全","意識障害","甲状腺疾患既往"]},
            {"disease": "甲状腺機能亢進症（未治療）","icd10":"E05.9","base_prob": 0.15,"boost_kw": ["動悸","体重減少","発汗","甲状腺腫"]},
            {"disease": "敗血症",                  "icd10": "A41.9","base_prob": 0.10,"boost_kw": ["感染源","CRP","PCT","WBC"]},
            {"disease": "悪性症候群",               "icd10": "G21.0","base_prob": 0.05,"boost_kw": ["抗精神病薬","筋強剛","CK上昇"]},
        ],
        "red_flags": ["Burch-Wartofskyスコア≥45→クリーゼ確定", "ICU管理"],
        "next_steps": ["甲状腺機能検査(FT4/TSH)", "PTU/チアマゾール", "β遮断薬", "ステロイド", "ICU管理"],
        "scoring_hints": ["Burch-Wartofsky score"],
        "urgency_override": "immediate",
    },
    {
        "id": "ADRENAL_CRISIS",
        "keywords": ["副腎クリーゼ", "副腎不全", "低Na", "低血圧", "ステロイド中断"],
        "diagnoses": [
            {"disease": "急性副腎不全（副腎クリーゼ）","icd10":"E27.2","base_prob": 0.68,"boost_kw": ["ステロイド中断","ショック","低Na","低血糖","色素沈着"]},
            {"disease": "敗血症性ショック",         "icd10": "A41.9","base_prob": 0.18,"boost_kw": ["感染源","発熱","CRP上昇","WBC"]},
            {"disease": "低ナトリウム血症（SIADH）","icd10":"E87.1","base_prob": 0.10,"boost_kw": ["低Na","尿Na上昇","肺炎","CNS疾患"]},
            {"disease": "心原性ショック",           "icd10": "R57.0","base_prob": 0.04,"boost_kw": ["TnI","BNP","心電図変化"]},
        ],
        "red_flags": ["ステロイド中断歴を必ず確認", "ヒドロコルチゾン100mg即注"],
        "next_steps": ["ヒドロコルチゾン100mg静注", "NS大量輸液", "血糖補正", "皮質醇採血"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    # ── 感染症 ──────────────────────────────────────────────────
    {
        "id": "SEPSIS",
        "keywords": ["敗血症", "SOFA", "SIRS", "臓器不全", "乳酸上昇", "菌血症"],
        "diagnoses": [
            {"disease": "敗血症性ショック",        "icd10": "A41.9","base_prob": 0.70,"boost_kw": ["臓器不全","乳酸>2","昇圧薬","培養陽性"]},
            {"disease": "重症肺炎（CAP重症型）",   "icd10": "J18.9","base_prob": 0.15,"boost_kw": ["肺炎","ICU","SpO2低下","CURB-65 4+"]},
            {"disease": "尿路性敗血症",            "icd10": "A41.9","base_prob": 0.10,"boost_kw": ["尿路感染","排尿痛","WBC尿","閉塞"]},
            {"disease": "腹腔内感染",              "icd10": "K65.0","base_prob": 0.05,"boost_kw": ["腹膜炎","穿孔","腹部手術後"]},
        ],
        "red_flags": ["SEP-1 bundle実施（1時間以内）", "血液培養→抗菌薬→乳酸→輸液"],
        "next_steps": ["血培2セット", "広域抗菌薬", "乳酸測定", "NS 30mL/kg", "ICU管理"],
        "scoring_hints": ["SOFA score", "qSOFA"],
        "urgency_override": "immediate",
    },
    {
        "id": "TB",
        "keywords": ["結核", "体重減少", "夜間発汗", "血痰", "渡航歴", "抗酸菌", "IGRA"],
        "diagnoses": [
            {"disease": "肺結核",                 "icd10": "A15.9","base_prob": 0.55,"boost_kw": ["渡航歴","夜間発汗","体重減少","血痰","上葉","空洞"]},
            {"disease": "悪性リンパ腫",           "icd10": "C85.9","base_prob": 0.20,"boost_kw": ["リンパ節腫大","B症状","LDH上昇"]},
            {"disease": "HIV/AIDS",               "icd10": "B24",  "base_prob": 0.12,"boost_kw": ["リスク行動","日和見感染","CD4低下"]},
            {"disease": "非結核性抗酸菌症（NTM）","icd10":"A31.0","base_prob": 0.08,"boost_kw": ["高齢女性","NTM","MAI"]},
            {"disease": "甲状腺機能亢進症",        "icd10": "E05.9","base_prob": 0.05,"boost_kw": ["動悸","発汗","FT4上昇"]},
        ],
        "red_flags": ["感染対策先行（陰圧個室・N95マスク）", "届出義務あり"],
        "next_steps": ["胸部X線/CT", "喀痰3回塗沫+GeneXpert", "HIV抗体", "IGRA"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    {
        "id": "ANAPHYLAXIS",
        "keywords": ["アナフィラキシー", "蕁麻疹", "喉頭浮腫", "アレルギー", "アドレナリン"],
        "diagnoses": [
            {"disease": "アナフィラキシー",        "icd10": "T78.2","base_prob": 0.85,"boost_kw": ["蕁麻疹","喉頭浮腫","血圧低下","抗原曝露","ハチ","食物"]},
            {"disease": "血管神経性浮腫",          "icd10": "T78.3","base_prob": 0.08,"boost_kw": ["ACE阻害薬","遺伝性","C1エステラーゼ"]},
            {"disease": "血管迷走神経反射",        "icd10": "R55",  "base_prob": 0.07,"boost_kw": ["注射後","痛み","迷走神経","徐脈"]},
        ],
        "red_flags": ["アドレナリン0.3mg筋注（大腿外側）が第一選択", "気道浮腫→早期挿管判断"],
        "next_steps": ["アドレナリン0.3-0.5mg筋注", "臥位+下肢挙上", "酸素投与", "抗ヒスタミン薬(補助)"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    # ── 腎・泌尿器 ───────────────────────────────────────────────
    {
        "id": "AKI",
        "keywords": ["急性腎障害", "Cr上昇", "乏尿", "無尿", "AKI", "BUN上昇"],
        "diagnoses": [
            {"disease": "急性腎障害（腎前性）",    "icd10": "N17.9","base_prob": 0.50,"boost_kw": ["脱水","低血圧","NSAID","造影剤","ショック"]},
            {"disease": "急性腎障害（腎性）",      "icd10": "N17.0","base_prob": 0.30,"boost_kw": ["急性腎炎","横紋筋融解","溶血性尿毒症"]},
            {"disease": "急性腎障害（腎後性）",    "icd10": "N17.2","base_prob": 0.15,"boost_kw": ["水腎症","閉塞","前立腺肥大","腫瘍"]},
            {"disease": "CKD急性増悪",            "icd10": "N18.9","base_prob": 0.05,"boost_kw": ["CKD既往","慢性"]},
        ],
        "red_flags": ["K>6.5 mEq/L→心電図+カルシウム静注", "無尿>6h→透析適応評価"],
        "next_steps": ["尿検査(沈渣/電解質)", "腎超音波(水腎症除外)", "NSAID中止", "適切な補液"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    {
        "id": "UROSEPSIS",
        "keywords": ["尿路感染", "膀胱炎", "腎盂腎炎", "排尿痛", "頻尿", "背部叩打痛"],
        "diagnoses": [
            {"disease": "腎盂腎炎",               "icd10": "N10",  "base_prob": 0.65,"boost_kw": ["背部叩打痛","CVA tenderness","発熱","WBC尿"]},
            {"disease": "膀胱炎",                 "icd10": "N30.0","base_prob": 0.25,"boost_kw": ["排尿痛","頻尿","血尿","発熱なし"]},
            {"disease": "尿路性敗血症",           "icd10": "A41.9","base_prob": 0.08,"boost_kw": ["敗血症","SOFA","発熱","WBC上昇","培養"]},
            {"disease": "前立腺炎（急性細菌性）", "icd10": "N41.0","base_prob": 0.02,"boost_kw": ["男性","会陰部痛","前立腺圧痛"]},
        ],
        "red_flags": ["敗血症基準（SOFA≥2）を満たす場合は尿路性敗血症"],
        "next_steps": ["尿検査+尿培養", "血液培養", "腎超音波", "抗菌薬（ST合剤/キノロン）"],
        "scoring_hints": ["qSOFA"],
        "urgency_override": None,
    },
    # ── 整形・外傷 ──────────────────────────────────────────────
    {
        "id": "TRAUMA_BLEED",
        "keywords": ["外傷", "出血", "多発外傷", "骨折", "ショック"],
        "diagnoses": [
            {"disease": "多発外傷+出血性ショック","icd10":"T07",   "base_prob": 0.75,"boost_kw": ["高エネルギー外傷","血圧低下","頻脈","意識障害"]},
            {"disease": "緊張性気胸",             "icd10": "J93.0","base_prob": 0.12,"boost_kw": ["患側消失","頸静脈怒張","縦隔偏位"]},
            {"disease": "心タンポナーデ",         "icd10": "I31.9","base_prob": 0.08,"boost_kw": ["Beck三徴","頸静脈怒張","心音減弱","低血圧"]},
            {"disease": "腹腔内出血（臓器損傷）", "icd10": "S36.9","base_prob": 0.05,"boost_kw": ["腹部外傷","腹膜刺激","FAST超音波"]},
        ],
        "red_flags": ["ATLS一次評価(ABCDE)", "大量輸血プロトコル(MTP)発動基準を確認"],
        "next_steps": ["FAST超音波", "外傷CT(全身)", "外傷外科コール", "大量輸血準備"],
        "scoring_hints": ["Shock index", "Revised Trauma Score"],
        "urgency_override": "immediate",
    },
    # ── 産科 ────────────────────────────────────────────────────
    {
        "id": "ECTOPIC",
        "keywords": ["異所性妊娠", "子宮外妊娠", "月経遅延", "β-hCG", "腹痛", "卵管"],
        "diagnoses": [
            {"disease": "子宮外妊娠（異所性妊娠）","icd10":"O00.9","base_prob": 0.75,"boost_kw": ["β-hCG陽性","子宮内胎嚢なし","月経遅延","腹痛"]},
            {"disease": "黄体嚢胞破裂",            "icd10": "N83.1","base_prob": 0.15,"boost_kw": ["卵巣","突然の激痛","腹水","月経後半"]},
            {"disease": "急性虫垂炎",              "icd10": "K37",  "base_prob": 0.07,"boost_kw": ["右下腹部","McBurney","WBC上昇"]},
            {"disease": "骨盤腹膜炎（PID）",       "icd10": "N73.0","base_prob": 0.03,"boost_kw": ["発熱","帯下異常","性交痛"]},
        ],
        "red_flags": ["βhCG>1500で子宮内胎嚢なし→緊急外科コール", "破裂後は失血性ショック"],
        "next_steps": ["尿妊娠反応", "経腟超音波", "β-hCG定量", "産婦人科緊急コール"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    {
        "id": "ECLAMPSIA",
        "keywords": ["子癇", "妊婦", "けいれん", "高血圧", "蛋白尿", "妊娠"],
        "diagnoses": [
            {"disease": "子癇発作",               "icd10": "O15.9","base_prob": 0.72,"boost_kw": ["妊婦","高血圧","けいれん","蛋白尿","浮腫"]},
            {"disease": "HELLP症候群",             "icd10": "O14.2","base_prob": 0.15,"boost_kw": ["溶血","血小板減少","肝酵素上昇","妊娠"]},
            {"disease": "羊水塞栓症",              "icd10": "O88.1","base_prob": 0.08,"boost_kw": ["分娩中","突然の心停止","DIC","呼吸不全"]},
            {"disease": "脳卒中（妊娠関連）",      "icd10": "I63.9","base_prob": 0.05,"boost_kw": ["片麻痺","失語","局所神経症状"]},
        ],
        "red_flags": ["MgSO4投与（再発予防）", "産婦人科+ICU"],
        "next_steps": ["硫酸Mg静注(子癇)", "降圧(ヒドララジン/ラベタロール)", "緊急分娩の検討"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    # ── 精神 ─────────────────────────────────────────────────────
    {
        "id": "DRUG_OD",
        "keywords": ["過量服薬", "自殺企図", "アセトアミノフェン", "ベンゾジアゼピン", "中毒"],
        "diagnoses": [
            {"disease": "アセトアミノフェン中毒",  "icd10": "T39.1","base_prob": 0.35,"boost_kw": ["アセトアミノフェン","解熱鎮痛薬","自殺企図","Rumack"]},
            {"disease": "ベンゾジアゼピン中毒",    "icd10": "T42.4","base_prob": 0.30,"boost_kw": ["BZD","抗不安薬","睡眠薬","呼吸抑制"]},
            {"disease": "三環系抗うつ薬中毒",      "icd10": "T43.0","base_prob": 0.20,"boost_kw": ["TCA","不整脈","QRS延長","意識障害"]},
            {"disease": "有機リン農薬中毒",         "icd10": "T60.0","base_prob": 0.15,"boost_kw": ["農薬","縮瞳","唾液分泌","SLUDGE"]},
        ],
        "red_flags": ["Rumack chartでNAC投与判断(APAP)", "QRS延長はNaHCO3", "縮瞳はアトロピン"],
        "next_steps": ["血中薬物濃度", "12誘導心電図(QRS/QTc)", "NAC/フルマゼニル/アトロピン", "中毒センター相談"],
        "scoring_hints": ["Rumack-Matthew nomogram（APAP）"],
        "urgency_override": "immediate",
    },
    {
        "id": "DELIRIUM",
        "keywords": ["せん妄", "急性混乱", "意識変容", "見当識障害", "夜間不穏", "CAM"],
        "diagnoses": [
            {"disease": "せん妄（身体因性）",      "icd10": "F05.9","base_prob": 0.65,"boost_kw": ["高齢","術後","発熱","低酸素","電解質異常"]},
            {"disease": "認知症（BPSD）",          "icd10": "F03",  "base_prob": 0.15,"boost_kw": ["慢性経過","認知症既往","夜間悪化"]},
            {"disease": "脳炎/髄膜炎",            "icd10": "G04.9","base_prob": 0.10,"boost_kw": ["発熱","頸部硬直","髄液異常"]},
            {"disease": "脳卒中",                  "icd10": "I63.9","base_prob": 0.10,"boost_kw": ["局所神経症状","突然発症","高血圧"]},
        ],
        "red_flags": ["身体疾患を必ず検索", "低酸素/低血糖を最初に除外"],
        "next_steps": ["CAM評価", "血糖/SpO2確認", "電解質/感染精査", "薬剤見直し(BZD/抗コリン)"],
        "scoring_hints": ["CAM (Confusion Assessment Method)"],
        "urgency_override": None,
    },
]
