EXTENDED_DD_RULES = [
    # ── 循環器 ──────────────────────────────────────────────────
    {
        "id": "ACS",
        "keywords": ["前胸部", "胸痛", "圧迫感", "放散痛", "ST上昇", "冷汗", "絞扼感"],
        "diagnoses": [
            {"disease": "急性冠症候群（ACS）",    "icd10": "I21.9", "base_prob": 0.68, "boost_kw": ["ST上昇","TnI","心電図","糖尿病","高血圧","喫煙"]},
            {"disease": "大動脈解離",             "icd10": "I71.0", "base_prob": 0.14, "boost_kw": ["引き裂く","血圧左右差","背部痛","マルファン"]},
            {"disease": "肺塞栓症",               "icd10": "I26.9", "base_prob": 0.10, "boost_kw": ["下肢浮腫","旅行歴","術後","Wells","D-dimer"]},
            {"disease": "急性心膜炎",             "icd10": "I30.9", "base_prob": 0.05, "boost_kw": ["体位","摩擦音","前傾位","SR上昇"]},
            {"disease": "食道痙攣",               "icd10": "K22.4", "base_prob": 0.03, "boost_kw": ["嚥下時","ニトロ有効","内視鏡"]},
        ],
        "red_flags": ["12誘導心電図即時確認", "TnI採血", "循環器緊急コール"],
        "next_steps": ["12誘導心電図", "採血(TnI/CK-MB/BNP)", "胸部X線", "心エコー"],
        "scoring_hints": ["HEART score算出を推奨"],
        "urgency_override": "immediate",
    },
    {
        "id": "AHF",
        "keywords": ["起座呼吸", "両下腿浮腫", "心不全", "BNP", "浮腫", "体重増加"],
        "diagnoses": [
            {"disease": "急性心不全（代償不全）",  "icd10": "I50.9", "base_prob": 0.72, "boost_kw": ["起座呼吸","心筋梗塞既往","BNP","両下腿浮腫"]},
            {"disease": "肺塞栓症",               "icd10": "I26.9", "base_prob": 0.12, "boost_kw": ["突然発症","片側浮腫","胸膜性胸痛"]},
            {"disease": "COPD増悪",               "icd10": "J44.1", "base_prob": 0.09, "boost_kw": ["喫煙歴","慢性咳嗽","過膨張"]},
            {"disease": "肺炎",                   "icd10": "J18.9", "base_prob": 0.07, "boost_kw": ["発熱","片側浸潤","CRP上昇"]},
        ],
        "red_flags": ["SpO2 90%以下は即時酸素投与", "起座呼吸は重篤な肺うっ血"],
        "next_steps": ["胸部X線(バット翼陰影)", "BNP/NT-proBNP", "心エコー", "ニトログリセリン+フロセミド"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    {
        "id": "AORTA",
        "keywords": ["大動脈", "引き裂く", "血圧左右差", "縦隔拡大", "解離"],
        "diagnoses": [
            {"disease": "急性大動脈解離",         "icd10": "I71.0", "base_prob": 0.78, "boost_kw": ["引き裂く","血圧左右差","マルファン","高血圧","突然"]},
            {"disease": "急性冠症候群（ACS）",    "icd10": "I21.9", "base_prob": 0.12, "boost_kw": ["ST変化","TnI","喫煙"]},
            {"disease": "大動脈瘤破裂",           "icd10": "I71.3", "base_prob": 0.10, "boost_kw": ["ショック","腹部拍動性腫瘤"]},
        ],
        "red_flags": ["造影CT緊急施行", "外科緊急コール", "血圧両側測定"],
        "next_steps": ["造影CT胸腹部", "外科コンサルト", "血圧両側測定+HR管理"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    # ── 神経 ────────────────────────────────────────────────────
    {
        "id": "SAH",
        "keywords": ["雷鳴頭痛", "thunderclap", "項部硬直", "羞明", "突然の激頭痛"],
        "diagnoses": [
            {"disease": "くも膜下出血（SAH）",    "icd10": "I60.9", "base_prob": 0.72, "boost_kw": ["雷鳴","突然","最悪","項部硬直","嘔吐"]},
            {"disease": "細菌性髄膜炎",           "icd10": "G00.9", "base_prob": 0.14, "boost_kw": ["発熱","意識","皮疹","点状出血"]},
            {"disease": "脳内出血",               "icd10": "I61.9", "base_prob": 0.08, "boost_kw": ["高血圧","抗凝固薬","局所神経"]},
            {"disease": "偏頭痛",                 "icd10": "G43.9", "base_prob": 0.06, "boost_kw": ["既往","前兆","若年","女性","光過敏"]},
        ],
        "red_flags": ["CT陰性でもLP必須(キサントクロミア)", "SAH否定まで緊急扱い"],
        "next_steps": ["頭部単純CT", "LP(CT陰性時)", "脳外科コール"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    {
        "id": "STROKE",
        "keywords": ["片麻痺", "構音障害", "顔面神経麻痺", "失語", "NIHSS", "脳卒中"],
        "diagnoses": [
            {"disease": "急性脳梗塞",             "icd10": "I63.9", "base_prob": 0.73, "boost_kw": ["心房細動","突然発症","片麻痺","失語"]},
            {"disease": "脳内出血",               "icd10": "I61.9", "base_prob": 0.16, "boost_kw": ["抗凝固薬","高血圧","頭痛","嘔吐"]},
            {"disease": "TIA",                    "icd10": "G45.9", "base_prob": 0.07, "boost_kw": ["症状消失","短時間","一過性"]},
            {"disease": "Todd麻痺",               "icd10": "G83.8", "base_prob": 0.04, "boost_kw": ["けいれん後","一過性","消失傾向"]},
        ],
        "red_flags": ["発症時刻確認必須(tPA適応判断)", "NIHSS評価"],
        "next_steps": ["頭部CT(出血除外)", "NIHSS評価", "脳卒中チーム緊急コール", "発症時刻確認"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    {
        "id": "MENINGITIS",
        "keywords": ["発熱", "頸部硬直", "髄膜", "Kernig", "点状出血", "項部"],
        "diagnoses": [
            {"disease": "細菌性髄膜炎",           "icd10": "G00.9", "base_prob": 0.73, "boost_kw": ["頸部硬直","点状出血","意識障害","若年","発熱"]},
            {"disease": "ウイルス性髄膜炎",       "icd10": "A87.9", "base_prob": 0.15, "boost_kw": ["比較的軽症","頭痛","嘔吐","発熱"]},
            {"disease": "ウイルス性脳炎（ヘルペス）", "icd10": "B00.4", "base_prob": 0.08, "boost_kw": ["局所神経","側頭葉","精神症状"]},
            {"disease": "くも膜下出血",           "icd10": "I60.9", "base_prob": 0.04, "boost_kw": ["雷鳴頭痛","突然"]},
        ],
        "red_flags": ["抗菌薬を30分以内に投与", "点状出血はDIC/Waterhouse-Friderichsen"],
        "next_steps": ["血培2セット採取→即セフトリアキソン2g", "デキサメサゾン（抗菌薬前）", "ICU管理"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    {
        "id": "SEIZURE",
        "keywords": ["けいれん", "てんかん", "発作", "意識消失", "痙攣"],
        "diagnoses": [
            {"disease": "てんかん重積状態（SE）",  "icd10": "G41.9", "base_prob": 0.55, "boost_kw": ["5分以上","繰り返し","意識回復なし"]},
            {"disease": "症候性てんかん（脳炎）", "icd10": "G40.9", "base_prob": 0.15, "boost_kw": ["発熱","頭痛","意識障害"]},
            {"disease": "低血糖発作",             "icd10": "E16.0", "base_prob": 0.12, "boost_kw": ["糖尿病","インスリン","血糖低値"]},
            {"disease": "電解質異常（低Na）",     "icd10": "E87.1", "base_prob": 0.10, "boost_kw": ["低Na","低Mg","低Ca"]},
            {"disease": "子癇発作",               "icd10": "O15.9", "base_prob": 0.08, "boost_kw": ["妊婦","妊娠","高血圧"]},
        ],
        "red_flags": ["5分以上持続→ジアゼパム/ミダゾラム即投与", "気道確保"],
        "next_steps": ["BZD投与(ジアゼパム5-10mg)", "血糖測定", "頭部CT", "EEG"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    # ── 呼吸器 ──────────────────────────────────────────────────
    {
        "id": "CAP",
        "keywords": ["発熱", "湿性咳嗽", "打診濁音", "浸潤影", "肺炎", "CRP上昇"],
        "diagnoses": [
            {"disease": "市中肺炎（CAP）",        "icd10": "J18.9", "base_prob": 0.70, "boost_kw": ["湿性咳","打診濁音","CRP","肺炎球菌"]},
            {"disease": "肺結核",                 "icd10": "A15.9", "base_prob": 0.12, "boost_kw": ["渡航歴","夜間発汗","体重減少","上葉","空洞"]},
            {"disease": "非定型肺炎",             "icd10": "J22",   "base_prob": 0.10, "boost_kw": ["乾性咳","若年","β-ラクタム無効","マイコプラズマ"]},
            {"disease": "肺癌+閉塞性肺炎",       "icd10": "C34.9", "base_prob": 0.05, "boost_kw": ["喫煙歴","繰り返す","高齢","血痰"]},
            {"disease": "好酸球性肺炎",           "icd10": "J82",   "base_prob": 0.03, "boost_kw": ["好酸球増加","抗菌薬無効","ステロイド反応"]},
        ],
        "red_flags": ["CURB-65スコアで入院適応判定", "結核疑いは陰圧個室+N95"],
        "next_steps": ["胸部X線", "採血(CBC/CRP/PCT)", "喀痰培養", "CURB-65算定"],
        "scoring_hints": ["CURB-65", "PSI/PORT"],
        "urgency_override": None,
    },
    {
        "id": "PE",
        "keywords": ["肺塞栓", "DVT", "D-dimer", "Wells", "突然の呼吸困難", "胸膜性胸痛"],
        "diagnoses": [
            {"disease": "肺塞栓症（PE）",         "icd10": "I26.9", "base_prob": 0.72, "boost_kw": ["片側浮腫","旅行歴","術後","Wells","D-dimer上昇"]},
            {"disease": "急性冠症候群",           "icd10": "I21.9", "base_prob": 0.12, "boost_kw": ["ST変化","TnI","喫煙"]},
            {"disease": "気胸",                   "icd10": "J93.9", "base_prob": 0.08, "boost_kw": ["若年","やせ形","患側呼吸音消失","叩打音"]},
            {"disease": "胸膜炎",                 "icd10": "R09.1", "base_prob": 0.08, "boost_kw": ["体位依存","胸膜摩擦音","発熱"]},
        ],
        "red_flags": ["Wellsスコア+D-dimer評価", "CTPA（CT肺動脈造影）"],
        "next_steps": ["Wells score算出", "D-dimer", "CTPA", "抗凝固療法開始"],
        "scoring_hints": ["Wells PE score"],
        "urgency_override": None,
    },
    {
        "id": "COPD",
        "keywords": ["COPD", "慢性閉塞性", "喘鳴", "慢性咳嗽", "SpO2低下", "呼吸困難"],
        "diagnoses": [
            {"disease": "COPD急性増悪",           "icd10": "J44.1", "base_prob": 0.65, "boost_kw": ["喫煙歴","慢性咳嗽","たるぼ型","呼気延長"]},
            {"disease": "気管支喘息発作",         "icd10": "J45.9", "base_prob": 0.18, "boost_kw": ["アレルギー歴","夜間","β2作動薬有効"]},
            {"disease": "心不全",                 "icd10": "I50.9", "base_prob": 0.12, "boost_kw": ["浮腫","BNP","起座呼吸"]},
            {"disease": "肺炎",                   "icd10": "J18.9", "base_prob": 0.05, "boost_kw": ["発熱","CRP上昇","浸潤影"]},
        ],
        "red_flags": ["pH<7.35→NIV/挿管", "PaCO2上昇は呼吸性アシドーシス"],
        "next_steps": ["酸素投与(目標SpO2 88-92%)", "気管支拡張薬吸入", "全身ステロイド", "血液ガス"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    {
        "id": "PNEUMOTHORAX",
        "keywords": ["気胸", "胸痛", "患側呼吸音消失", "叩打音", "やせ型"],
        "diagnoses": [
            {"disease": "自然気胸",               "icd10": "J93.1", "base_prob": 0.72, "boost_kw": ["若年","やせ形","突然","患側消失"]},
            {"disease": "緊張性気胸",             "icd10": "J93.0", "base_prob": 0.15, "boost_kw": ["ショック","縦隔偏位","頸静脈怒張","外傷"]},
            {"disease": "血胸",                   "icd10": "J94.2", "base_prob": 0.08, "boost_kw": ["外傷","鈍的","貫通"]},
            {"disease": "肺塞栓症",               "icd10": "I26.9", "base_prob": 0.05, "boost_kw": ["D-dimer","浮腫","旅行"]},
        ],
        "red_flags": ["緊張性気胸は即刻胸腔穿刺（診断的兼治療的）"],
        "next_steps": ["胸部X線", "胸腔穿刺/ドレナージ（緊張性）", "呼吸器科コール"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    # ── 消化器 ──────────────────────────────────────────────────
    {
        "id": "APPENDICITIS",
        "keywords": ["右下腹部", "McBurney", "虫垂", "反跳痛", "Rovsing"],
        "diagnoses": [
            {"disease": "急性虫垂炎",             "icd10": "K37",   "base_prob": 0.65, "boost_kw": ["McBurney","反跳痛","WBC上昇","CRP上昇","CT"]},
            {"disease": "卵巣捻転",               "icd10": "N83.5", "base_prob": 0.12, "boost_kw": ["女性","骨盤痛","間歇性","超音波"]},
            {"disease": "異所性妊娠",             "icd10": "O00.9", "base_prob": 0.10, "boost_kw": ["女性","月経遅延","β-hCG","妊娠"]},
            {"disease": "右卵巣嚢腫破裂",         "icd10": "N83.1", "base_prob": 0.08, "boost_kw": ["突然","激痛","女性","腹水"]},
            {"disease": "腸管膜リンパ節炎",       "icd10": "I88.0", "base_prob": 0.05, "boost_kw": ["上気道炎先行","小児","若年"]},
        ],
        "red_flags": ["女性は必ず尿妊娠反応（β-hCG）確認", "穿孔後は汎発性腹膜炎"],
        "next_steps": ["尿妊娠反応（女性）", "腹部超音波", "腹部CT", "外科コンサルト"],
        "scoring_hints": ["Alvarado score", "AIR score"],
        "urgency_override": None,
    },
    {
        "id": "CHOLANGITIS",
        "keywords": ["黄疸", "胆管", "Charcot", "胆石", "Murphy", "季肋部"],
        "diagnoses": [
            {"disease": "急性胆管炎",             "icd10": "K83.0", "base_prob": 0.62, "boost_kw": ["黄疸","Charcot","胆石","胆管拡張","発熱"]},
            {"disease": "急性胆嚢炎",             "icd10": "K81.0", "base_prob": 0.20, "boost_kw": ["Murphy陽性","壁肥厚","黄疸なし"]},
            {"disease": "急性膵炎",               "icd10": "K85.9", "base_prob": 0.12, "boost_kw": ["アミラーゼ","リパーゼ","背部放散痛","飲酒"]},
            {"disease": "肝膿瘍",                 "icd10": "K75.0", "base_prob": 0.06, "boost_kw": ["アメーバ","海外","CTで低吸収"]},
        ],
        "red_flags": ["Charcot三徴=胆管炎", "Reynolds五徴（+ショック+意識障害）は重症"],
        "next_steps": ["腹部超音波", "採血(肝機能/GGT/ALP/培養)", "抗菌薬", "緊急ERCP/PTCD"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    {
        "id": "PANCREATITIS",
        "keywords": ["膵炎", "アミラーゼ", "リパーゼ", "心窩部", "背部放散痛", "飲酒"],
        "diagnoses": [
            {"disease": "急性膵炎",               "icd10": "K85.9", "base_prob": 0.78, "boost_kw": ["アミラーゼ","リパーゼ","飲酒","胆石","CT"]},
            {"disease": "消化性潰瘍穿孔",         "icd10": "K27.1", "base_prob": 0.10, "boost_kw": ["突然","腹部全体","腹膜刺激","free air"]},
            {"disease": "SMA閉塞",                "icd10": "K55.0", "base_prob": 0.07, "boost_kw": ["突然","pain out of proportion","心房細動"]},
            {"disease": "急性胆嚢炎",             "icd10": "K81.0", "base_prob": 0.05, "boost_kw": ["Murphy","季肋部","超音波"]},
        ],
        "red_flags": ["Ranson基準/BISAPスコアで重症度評価", "SMA閉塞は死亡率80%以上"],
        "next_steps": ["採血(アミラーゼ/リパーゼ/CRP)", "腹部CT(造影)", "禁食+輸液", "Ranson評価"],
        "scoring_hints": ["Ranson criteria", "BISAP score"],
        "urgency_override": None,
    },
    {
        "id": "GI_BLEED",
        "keywords": ["吐血", "下血", "タール便", "血便", "消化管出血", "Hb低下", "失血", "黒色便", "血性"],
        "diagnoses": [
            {"disease": "消化性潰瘍出血（上部GI）","icd10":"K27.4","base_prob": 0.50,"boost_kw": ["吐血","NSAID","H.pylori","コーヒー残渣様"]},
            {"disease": "大腸出血（下部GI）",      "icd10": "K92.1","base_prob": 0.25,"boost_kw": ["鮮血便","大腸憩室","大腸癌","直腸癌"]},
            {"disease": "食道静脈瘤破裂",          "icd10": "I85.0","base_prob": 0.15,"boost_kw": ["肝硬変","アルコール","大量吐血"]},
            {"disease": "Mallory-Weiss症候群",     "icd10": "K22.6","base_prob": 0.10,"boost_kw": ["嘔吐後","アルコール","少量"]},
        ],
        "red_flags": ["大量吐血はショック管理優先", "肝硬変既往は食道静脈瘤を第一に"],
        "next_steps": ["大口径ルート2本確保", "輸血(Hb<7g/dL)", "消化器内視鏡緊急", "消化器コール"],
        "scoring_hints": ["Blatchford score（上部GI）", "Glasgow-Blatchford score"],
        "urgency_override": None,
    },
    # ── 内分泌・代謝 ────────────────────────────────────────────
    {
        "id": "DKA",
        "keywords": ["クスマウル", "DKA", "ケトン", "血糖", "糖尿", "意識障害", "代謝性アシドーシス"],
        "diagnoses": [
            {"disease": "糖尿病性ケトアシドーシス（DKA）","icd10":"E10.1","base_prob": 0.78,"boost_kw": ["1型","インスリン中断","クスマウル","ケトン","pH<7.3"]},
            {"disease": "高血糖高浸透圧症候群（HHS）","icd10":"E11.0","base_prob": 0.10,"boost_kw": ["2型","血糖>600","ケトーシス軽度"]},
            {"disease": "乳酸アシドーシス",         "icd10": "E87.2","base_prob": 0.07,"boost_kw": ["ビグアナイド","腎不全","ショック","乳酸>4"]},
            {"disease": "アルコール性ケトアシドーシス","icd10":"E87.2","base_prob": 0.05,"boost_kw": ["飲酒","血糖正常〜低値","嘔吐"]},
        ],
        "red_flags": ["クスマウル呼吸=重篤なアシドーシス", "K値モニタリング必須（インスリン投与前）"],
        "next_steps": ["血糖/ガス/電解質/ケトン", "輸液(NS 1L/h)", "インスリン持続", "K補充"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    {
        "id": "HYPOGLYCEMIA",
        "keywords": ["低血糖", "冷汗", "振戦", "動悸", "血糖低下"],
        "diagnoses": [
            {"disease": "薬剤性低血糖（SU/インスリン）","icd10":"E16.0","base_prob": 0.72,"boost_kw": ["インスリン","スルホニル尿素","糖尿病"]},
            {"disease": "インスリノーマ",           "icd10": "D13.7","base_prob": 0.10,"boost_kw": ["反復性","空腹時","Whipple三徴"]},
            {"disease": "副腎不全",                 "icd10": "E27.4","base_prob": 0.10,"boost_kw": ["副腎","ステロイド中断","色素沈着","低Na"]},
            {"disease": "劇症1型糖尿病",            "icd10": "E10.9","base_prob": 0.08,"boost_kw": ["急激発症","flu様","ケトーシス軽度"]},
        ],
        "red_flags": ["血糖<50mg/dL→即座に補糖", "SU剤による低血糖は遷延→入院"],
        "next_steps": ["血糖測定", "50%ブドウ糖20-40mL静注（意識障害時）", "原因薬剤確認"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    {
        "id": "THYROID_CRISIS",
        "keywords": ["甲状腺クリーゼ", "甲状腺", "頻脈", "高体温", "眼球突出", "Burch-Wartofsky"],
        "diagnoses": [
            {"disease": "甲状腺クリーゼ",          "icd10": "E05.5","base_prob": 0.70,"boost_kw": ["頻脈","高体温","心不全","意識障害","甲状腺疾患既往"]},
            {"disease": "甲状腺機能亢進症（未治療）","icd10":"E05.9","base_prob": 0.15,"boost_kw": ["動悸","体重減少","発汗","甲状腺腫"]},
            {"disease": "敗血症",                  "icd10": "A41.9","base_prob": 0.10,"boost_kw": ["感染源","CRP","PCT","WBC"]},
            {"disease": "悪性症候群",               "icd10": "G21.0","base_prob": 0.05,"boost_kw": ["抗精神病薬","筋強剛","CK上昇"]},
        ],
        "red_flags": ["Burch-Wartofskyスコア≥45→クリーゼ確定", "ICU管理"],
        "next_steps": ["甲状腺機能検査(FT4/TSH)", "PTU/チアマゾール", "β遮断薬", "ステロイド", "ICU管理"],
        "scoring_hints": ["Burch-Wartofsky score"],
        "urgency_override": "immediate",
    },
    {
        "id": "ADRENAL_CRISIS",
        "keywords": ["副腎クリーゼ", "副腎不全", "低Na", "低血圧", "ステロイド中断"],
        "diagnoses": [
            {"disease": "急性副腎不全（副腎クリーゼ）","icd10":"E27.2","base_prob": 0.68,"boost_kw": ["ステロイド中断","ショック","低Na","低血糖","色素沈着"]},
            {"disease": "敗血症性ショック",         "icd10": "A41.9","base_prob": 0.18,"boost_kw": ["感染源","発熱","CRP上昇","WBC"]},
            {"disease": "低ナトリウム血症（SIADH）","icd10":"E87.1","base_prob": 0.10,"boost_kw": ["低Na","尿Na上昇","肺炎","CNS疾患"]},
            {"disease": "心原性ショック",           "icd10": "R57.0","base_prob": 0.04,"boost_kw": ["TnI","BNP","心電図変化"]},
        ],
        "red_flags": ["ステロイド中断歴を必ず確認", "ヒドロコルチゾン100mg即注"],
        "next_steps": ["ヒドロコルチゾン100mg静注", "NS大量輸液", "血糖補正", "皮質醇採血"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    # ── 感染症 ──────────────────────────────────────────────────
    {
        "id": "SEPSIS",
        "keywords": ["敗血症", "SOFA", "SIRS", "臓器不全", "乳酸上昇", "菌血症"],
        "diagnoses": [
            {"disease": "敗血症性ショック",        "icd10": "A41.9","base_prob": 0.70,"boost_kw": ["臓器不全","乳酸>2","昇圧薬","培養陽性"]},
            {"disease": "重症肺炎（CAP重症型）",   "icd10": "J18.9","base_prob": 0.15,"boost_kw": ["肺炎","ICU","SpO2低下","CURB-65 4+"]},
            {"disease": "尿路性敗血症",            "icd10": "A41.9","base_prob": 0.10,"boost_kw": ["尿路感染","排尿痛","WBC尿","閉塞"]},
            {"disease": "腹腔内感染",              "icd10": "K65.0","base_prob": 0.05,"boost_kw": ["腹膜炎","穿孔","腹部手術後"]},
        ],
        "red_flags": ["SEP-1 bundle実施（1時間以内）", "血液培養→抗菌薬→乳酸→輸液"],
        "next_steps": ["血培2セット", "広域抗菌薬", "乳酸測定", "NS 30mL/kg", "ICU管理"],
        "scoring_hints": ["SOFA score", "qSOFA"],
        "urgency_override": "immediate",
    },
    {
        "id": "TB",
        "keywords": ["結核", "体重減少", "夜間発汗", "血痰", "渡航歴", "抗酸菌", "IGRA"],
        "diagnoses": [
            {"disease": "肺結核",                 "icd10": "A15.9","base_prob": 0.55,"boost_kw": ["渡航歴","夜間発汗","体重減少","血痰","上葉","空洞"]},
            {"disease": "悪性リンパ腫",           "icd10": "C85.9","base_prob": 0.20,"boost_kw": ["リンパ節腫大","B症状","LDH上昇"]},
            {"disease": "HIV/AIDS",               "icd10": "B24",  "base_prob": 0.12,"boost_kw": ["リスク行動","日和見感染","CD4低下"]},
            {"disease": "非結核性抗酸菌症（NTM）","icd10":"A31.0","base_prob": 0.08,"boost_kw": ["高齢女性","NTM","MAI"]},
            {"disease": "甲状腺機能亢進症",        "icd10": "E05.9","base_prob": 0.05,"boost_kw": ["動悸","発汗","FT4上昇"]},
        ],
        "red_flags": ["感染対策先行（陰圧個室・N95マスク）", "届出義務あり"],
        "next_steps": ["胸部X線/CT", "喀痰3回塗沫+GeneXpert", "HIV抗体", "IGRA"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    {
        "id": "ANAPHYLAXIS",
        "keywords": ["アナフィラキシー", "蕁麻疹", "喉頭浮腫", "アレルギー", "アドレナリン"],
        "diagnoses": [
            {"disease": "アナフィラキシー",        "icd10": "T78.2","base_prob": 0.85,"boost_kw": ["蕁麻疹","喉頭浮腫","血圧低下","抗原曝露","ハチ","食物"]},
            {"disease": "血管神経性浮腫",          "icd10": "T78.3","base_prob": 0.08,"boost_kw": ["ACE阻害薬","遺伝性","C1エステラーゼ"]},
            {"disease": "血管迷走神経反射",        "icd10": "R55",  "base_prob": 0.07,"boost_kw": ["注射後","痛み","迷走神経","徐脈"]},
        ],
        "red_flags": ["アドレナリン0.3mg筋注（大腿外側）が第一選択", "気道浮腫→早期挿管判断"],
        "next_steps": ["アドレナリン0.3-0.5mg筋注", "臥位+下肢挙上", "酸素投与", "抗ヒスタミン薬(補助)"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    # ── 腎・泌尿器 ───────────────────────────────────────────────
    {
        "id": "AKI",
        "keywords": ["急性腎障害", "Cr上昇", "乏尿", "無尿", "AKI", "BUN上昇"],
        "diagnoses": [
            {"disease": "急性腎障害（腎前性）",    "icd10": "N17.9","base_prob": 0.50,"boost_kw": ["脱水","低血圧","NSAID","造影剤","ショック"]},
            {"disease": "急性腎障害（腎性）",      "icd10": "N17.0","base_prob": 0.30,"boost_kw": ["急性腎炎","横紋筋融解","溶血性尿毒症"]},
            {"disease": "急性腎障害（腎後性）",    "icd10": "N17.2","base_prob": 0.15,"boost_kw": ["水腎症","閉塞","前立腺肥大","腫瘍"]},
            {"disease": "CKD急性増悪",            "icd10": "N18.9","base_prob": 0.05,"boost_kw": ["CKD既往","慢性"]},
        ],
        "red_flags": ["K>6.5 mEq/L→心電図+カルシウム静注", "無尿>6h→透析適応評価"],
        "next_steps": ["尿検査(沈渣/電解質)", "腎超音波(水腎症除外)", "NSAID中止", "適切な補液"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    {
        "id": "UROSEPSIS",
        "keywords": ["尿路感染", "膀胱炎", "腎盂腎炎", "排尿痛", "頻尿", "背部叩打痛"],
        "diagnoses": [
            {"disease": "腎盂腎炎",               "icd10": "N10",  "base_prob": 0.65,"boost_kw": ["背部叩打痛","CVA tenderness","発熱","WBC尿"]},
            {"disease": "膀胱炎",                 "icd10": "N30.0","base_prob": 0.25,"boost_kw": ["排尿痛","頻尿","血尿","発熱なし"]},
            {"disease": "尿路性敗血症",           "icd10": "A41.9","base_prob": 0.08,"boost_kw": ["敗血症","SOFA","発熱","WBC上昇","培養"]},
            {"disease": "前立腺炎（急性細菌性）", "icd10": "N41.0","base_prob": 0.02,"boost_kw": ["男性","会陰部痛","前立腺圧痛"]},
        ],
        "red_flags": ["敗血症基準（SOFA≥2）を満たす場合は尿路性敗血症"],
        "next_steps": ["尿検査+尿培養", "血液培養", "腎超音波", "抗菌薬（ST合剤/キノロン）"],
        "scoring_hints": ["qSOFA"],
        "urgency_override": None,
    },
    # ── 整形・外傷 ──────────────────────────────────────────────
    {
        "id": "TRAUMA_BLEED",
        "keywords": ["外傷", "出血", "多発外傷", "骨折", "ショック"],
        "diagnoses": [
            {"disease": "多発外傷+出血性ショック","icd10":"T07",   "base_prob": 0.75,"boost_kw": ["高エネルギー外傷","血圧低下","頻脈","意識障害"]},
            {"disease": "緊張性気胸",             "icd10": "J93.0","base_prob": 0.12,"boost_kw": ["患側消失","頸静脈怒張","縦隔偏位"]},
            {"disease": "心タンポナーデ",         "icd10": "I31.9","base_prob": 0.08,"boost_kw": ["Beck三徴","頸静脈怒張","心音減弱","低血圧"]},
            {"disease": "腹腔内出血（臓器損傷）", "icd10": "S36.9","base_prob": 0.05,"boost_kw": ["腹部外傷","腹膜刺激","FAST超音波"]},
        ],
        "red_flags": ["ATLS一次評価(ABCDE)", "大量輸血プロトコル(MTP)発動基準を確認"],
        "next_steps": ["FAST超音波", "外傷CT(全身)", "外傷外科コール", "大量輸血準備"],
        "scoring_hints": ["Shock index", "Revised Trauma Score"],
        "urgency_override": "immediate",
    },
    # ── 産科 ────────────────────────────────────────────────────
    {
        "id": "ECTOPIC",
        "keywords": ["異所性妊娠", "子宮外妊娠", "月経遅延", "β-hCG", "腹痛", "卵管"],
        "diagnoses": [
            {"disease": "子宮外妊娠（異所性妊娠）","icd10":"O00.9","base_prob": 0.75,"boost_kw": ["β-hCG陽性","子宮内胎嚢なし","月経遅延","腹痛"]},
            {"disease": "黄体嚢胞破裂",            "icd10": "N83.1","base_prob": 0.15,"boost_kw": ["卵巣","突然の激痛","腹水","月経後半"]},
            {"disease": "急性虫垂炎",              "icd10": "K37",  "base_prob": 0.07,"boost_kw": ["右下腹部","McBurney","WBC上昇"]},
            {"disease": "骨盤腹膜炎（PID）",       "icd10": "N73.0","base_prob": 0.03,"boost_kw": ["発熱","帯下異常","性交痛"]},
        ],
        "red_flags": ["βhCG>1500で子宮内胎嚢なし→緊急外科コール", "破裂後は失血性ショック"],
        "next_steps": ["尿妊娠反応", "経腟超音波", "β-hCG定量", "産婦人科緊急コール"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    {
        "id": "ECLAMPSIA",
        "keywords": ["子癇", "妊婦", "けいれん", "高血圧", "蛋白尿", "妊娠"],
        "diagnoses": [
            {"disease": "子癇発作",               "icd10": "O15.9","base_prob": 0.72,"boost_kw": ["妊婦","高血圧","けいれん","蛋白尿","浮腫"]},
            {"disease": "HELLP症候群",             "icd10": "O14.2","base_prob": 0.15,"boost_kw": ["溶血","血小板減少","肝酵素上昇","妊娠"]},
            {"disease": "羊水塞栓症",              "icd10": "O88.1","base_prob": 0.08,"boost_kw": ["分娩中","突然の心停止","DIC","呼吸不全"]},
            {"disease": "脳卒中（妊娠関連）",      "icd10": "I63.9","base_prob": 0.05,"boost_kw": ["片麻痺","失語","局所神経症状"]},
        ],
        "red_flags": ["MgSO4投与（再発予防）", "産婦人科+ICU"],
        "next_steps": ["硫酸Mg静注(子癇)", "降圧(ヒドララジン/ラベタロール)", "緊急分娩の検討"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    # ── 精神 ─────────────────────────────────────────────────────
    {
        "id": "DRUG_OD",
        "keywords": ["過量服薬", "自殺企図", "アセトアミノフェン", "ベンゾジアゼピン", "中毒"],
        "diagnoses": [
            {"disease": "アセトアミノフェン中毒",  "icd10": "T39.1","base_prob": 0.35,"boost_kw": ["アセトアミノフェン","解熱鎮痛薬","自殺企図","Rumack"]},
            {"disease": "ベンゾジアゼピン中毒",    "icd10": "T42.4","base_prob": 0.30,"boost_kw": ["BZD","抗不安薬","睡眠薬","呼吸抑制"]},
            {"disease": "三環系抗うつ薬中毒",      "icd10": "T43.0","base_prob": 0.20,"boost_kw": ["TCA","不整脈","QRS延長","意識障害"]},
            {"disease": "有機リン農薬中毒",         "icd10": "T60.0","base_prob": 0.15,"boost_kw": ["農薬","縮瞳","唾液分泌","SLUDGE"]},
        ],
        "red_flags": ["Rumack chartでNAC投与判断(APAP)", "QRS延長はNaHCO3", "縮瞳はアトロピン"],
        "next_steps": ["血中薬物濃度", "12誘導心電図(QRS/QTc)", "NAC/フルマゼニル/アトロピン", "中毒センター相談"],
        "scoring_hints": ["Rumack-Matthew nomogram（APAP）"],
        "urgency_override": "immediate",
    },
    {
        "id": "DELIRIUM",
        "keywords": ["せん妄", "急性混乱", "意識変容", "見当識障害", "夜間不穏", "CAM"],
        "diagnoses": [
            {"disease": "せん妄（身体因性）",      "icd10": "F05.9","base_prob": 0.65,"boost_kw": ["高齢","術後","発熱","低酸素","電解質異常"]},
            {"disease": "認知症（BPSD）",          "icd10": "F03",  "base_prob": 0.15,"boost_kw": ["慢性経過","認知症既往","夜間悪化"]},
            {"disease": "脳炎/髄膜炎",            "icd10": "G04.9","base_prob": 0.10,"boost_kw": ["発熱","頸部硬直","髄液異常"]},
            {"disease": "脳卒中",                  "icd10": "I63.9","base_prob": 0.10,"boost_kw": ["局所神経症状","突然発症","高血圧"]},
        ],
        "red_flags": ["身体疾患を必ず検索", "低酸素/低血糖を最初に除外"],
        "next_steps": ["CAM評価", "血糖/SpO2確認", "電解質/感染精査", "薬剤見直し(BZD/抗コリン)"],
        "scoring_hints": ["CAM (Confusion Assessment Method)"],
        "urgency_override": None,
    },
]

# ── ベンチマーク弱点補強ルール ────────────────────────────────
SUPPLEMENT_RULES = [
    {
        "id": "NEPHROLITHIASIS",
        "keywords": ["尿管結石", "腎結石", "疝痛", "CVA", "腰痛", "血尿", "叩打痛"],
        "diagnoses": [
            {"disease": "尿管結石", "icd10": "N20.1", "base_prob": 0.78,
             "boost_kw": ["疝痛", "血尿", "CVA", "叩打痛", "突然"]},
            {"disease": "腎盂腎炎", "icd10": "N10", "base_prob": 0.12,
             "boost_kw": ["発熱", "膿尿", "尿WBC"]},
            {"disease": "大動脈解離", "icd10": "I71.0", "base_prob": 0.06,
             "boost_kw": ["高血圧", "引き裂く", "側腹部"]},
            {"disease": "虫垂炎", "icd10": "K37", "base_prob": 0.04,
             "boost_kw": ["右下腹部", "McBurney"]},
        ],
        "red_flags": ["側腹部疝痛は尿管結石の典型", "水腎症→閉塞性腎盂腎炎に注意"],
        "next_steps": ["尿検査(赤血球)", "腹部超音波/CT", "疼痛管理(NSAIDs/オピオイド)"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    {
        "id": "SYNCOPE",
        "keywords": ["失神", "意識消失", "眼前暗黒感", "立ちくらみ", "転倒"],
        "diagnoses": [
            {"disease": "血管迷走神経性失神（VVS）", "icd10": "R55", "base_prob": 0.55,
             "boost_kw": ["起立", "痛み", "感情", "前駆症状", "若年"]},
            {"disease": "起立性低血圧", "icd10": "I95.1", "base_prob": 0.15,
             "boost_kw": ["起立時", "降圧薬", "脱水", "高齢"]},
            {"disease": "不整脈（心原性失神）", "icd10": "R55", "base_prob": 0.15,
             "boost_kw": ["突然", "運動中", "前駆症状なし", "心疾患既往"]},
            {"disease": "てんかん発作後", "icd10": "G40.9", "base_prob": 0.10,
             "boost_kw": ["痙攣", "咬舌", "尿失禁", "意識回復遅延"]},
            {"disease": "TIA/椎骨脳底動脈症状", "icd10": "G45.9", "base_prob": 0.05,
             "boost_kw": ["後頭部痛", "めまい", "複視", "高齢"]},
        ],
        "red_flags": ["運動中の失神は心原性を除外", "ECG必須（QT延長・ブルガダ）"],
        "next_steps": ["12誘導心電図", "起立性血圧測定", "血糖測定", "ホルター心電図検討"],
        "scoring_hints": ["EGSYS score"],
        "urgency_override": None,
    },
    {
        "id": "SLE",
        "keywords": ["全身性エリテマトーデス", "SLE", "蝶形紅斑", "ANA", "関節痛", "光線過敏"],
        "diagnoses": [
            {"disease": "全身性エリテマトーデス（SLE）", "icd10": "M32.9", "base_prob": 0.65,
             "boost_kw": ["蝶形紅斑", "ANA陽性", "光線過敏", "関節炎", "若年女性"]},
            {"disease": "皮膚筋炎/多発性筋炎", "icd10": "M33.9", "base_prob": 0.15,
             "boost_kw": ["筋力低下", "CPK上昇", "ヘリオトロープ"]},
            {"disease": "関節リウマチ（RA）", "icd10": "M05.9", "base_prob": 0.12,
             "boost_kw": ["RF陽性", "抗CCP抗体", "対称性関節炎", "朝のこわばり"]},
            {"disease": "混合性結合組織病（MCTD）", "icd10": "M35.1", "base_prob": 0.08,
             "boost_kw": ["抗U1-RNP抗体", "レイノー", "混合症状"]},
        ],
        "red_flags": ["ループス腎炎→尿検査必須", "抗リン脂質抗体症候群→血栓リスク"],
        "next_steps": ["ANA/抗dsDNA抗体/補体(C3/C4)", "尿検査(蛋白/赤血球)", "血算/生化学"],
        "scoring_hints": ["SLICC分類基準2012"],
        "urgency_override": None,
    },
    {
        "id": "ASTHMA",
        "keywords": ["喘息", "気管支喘息", "喘鳴", "呼吸困難", "アレルギー", "アトピー"],
        "diagnoses": [
            {"disease": "気管支喘息急性発作", "icd10": "J45.9", "base_prob": 0.72,
             "boost_kw": ["喘鳴", "夜間", "アレルギー歴", "β2作動薬有効", "アトピー"]},
            {"disease": "COPD急性増悪", "icd10": "J44.1", "base_prob": 0.15,
             "boost_kw": ["喫煙歴長期", "慢性咳嗽", "高齢", "β2効果不十分"]},
            {"disease": "アナフィラキシー", "icd10": "T78.2", "base_prob": 0.08,
             "boost_kw": ["蕁麻疹", "アレルゲン曝露", "循環不全"]},
            {"disease": "心因性過換気症候群", "icd10": "F45.3", "base_prob": 0.05,
             "boost_kw": ["手足のしびれ", "ストレス", "呼吸数過多", "SpO2正常"]},
        ],
        "red_flags": ["重症発作: 会話不能・チアノーゼ→ICU", "MgSO4の適応を評価"],
        "next_steps": ["SABA吸入(β2作動薬)", "全身ステロイド", "酸素投与", "重症度評価(GINA)"],
        "scoring_hints": ["GINA重症度分類"],
        "urgency_override": None,
    },
    {
        "id": "TIA",
        "keywords": ["TIA", "一過性脳虚血", "一時的麻痺", "一過性", "症状消失", "ABCD2"],
        "diagnoses": [
            {"disease": "一過性脳虚血発作（TIA）", "icd10": "G45.9", "base_prob": 0.70,
             "boost_kw": ["症状消失", "一過性", "24時間以内", "麻痺", "失語"]},
            {"disease": "複雑型偏頭痛（前兆あり）", "icd10": "G43.1", "base_prob": 0.15,
             "boost_kw": ["頭痛", "閃輝暗点", "若年", "偏頭痛既往"]},
            {"disease": "低血糖", "icd10": "E16.0", "base_prob": 0.10,
             "boost_kw": ["糖尿病", "インスリン", "血糖低値"]},
            {"disease": "局所てんかん", "icd10": "G40.9", "base_prob": 0.05,
             "boost_kw": ["けいれん", "Todd麻痺", "てんかん既往"]},
        ],
        "red_flags": ["ABCD2スコア≥4→入院必須", "48時間以内の脳卒中リスク最大20%"],
        "next_steps": ["頭部MRI/MRA", "ABCD2スコア算定", "心電図(AF除外)", "血糖測定"],
        "scoring_hints": ["ABCD2 score"],
        "urgency_override": "urgent",
    },
    # ── 腫瘍救急・リウマチ ────────────────────────────────────────
    {
        "id": "FEBRILE_NEUTROPENIA",
        "keywords": ["発熱", "ANC", "好中球", "化学療法", "免疫抑制", "好中球減少"],
        "diagnoses": [
            {"disease": "発熱性好中球減少症（FN）", "icd10": "D70.1", "base_prob": 0.70,
             "boost_kw": ["ANC", "好中球", "化学療法", "ナディア", "500", "抗がん剤"]},
            {"disease": "敗血症（FN合併）", "icd10": "A41.9", "base_prob": 0.15,
             "boost_kw": ["血圧低下", "乳酸", "SOFA", "臓器不全", "菌血症"]},
            {"disease": "侵襲性真菌症", "icd10": "B49", "base_prob": 0.10,
             "boost_kw": ["抗菌薬無効", "4日以上", "真菌", "カンジダ", "アスペルギルス"]},
            {"disease": "ウイルス感染症（CMV等）", "icd10": "B25.9", "base_prob": 0.05,
             "boost_kw": ["CMV", "ウイルス", "移植後", "再活性化"]},
        ],
        "red_flags": ["血液培養2セット採取後に広域抗菌薬を1時間以内に投与", "MASCC低リスクでも入院判断を慎重に"],
        "next_steps": ["血液培養2セット採取", "広域抗菌薬（セフェピム/PIPC-TAZ）", "血算・CRP・Cr・電解質", "感染源検索（胸部X線・尿培養）"],
        "scoring_hints": ["MASCCスコア"],
        "urgency_override": "immediate",
    },
    {
        "id": "TUMOR_LYSIS",
        "keywords": ["TLS", "高カリウム", "高リン", "高尿酸", "低カルシウム", "腫瘍崩壊"],
        "diagnoses": [
            {"disease": "腫瘍崩壊症候群（TLS）", "icd10": "E88.3", "base_prob": 0.75,
             "boost_kw": ["TLS", "高K", "高リン", "高尿酸", "低Ca", "化学療法後", "白血病", "リンパ腫"]},
            {"disease": "AKI（腫瘍崩壊関連）", "icd10": "N17.9", "base_prob": 0.12,
             "boost_kw": ["Cr上昇", "乏尿", "腎不全"]},
            {"disease": "高カリウム血症（単独）", "icd10": "E87.5", "base_prob": 0.08,
             "boost_kw": ["心電図変化", "テント状T波", "K上昇"]},
            {"disease": "横紋筋融解症", "icd10": "M62.9", "base_prob": 0.05,
             "boost_kw": ["CK上昇", "ミオグロビン尿", "筋肉痛"]},
        ],
        "red_flags": ["K>6.0mEq/L→心電図確認＋カルシウム静注", "ラスブリカーゼは高リスク・既発症例に使用", "透析適応を早期評価"],
        "next_steps": ["電解質（K・Ca・P・Na）", "尿酸・Cr・LDH", "輸液（2〜3L/m²/日）", "ラスブリカーゼまたはアロプリノール"],
        "scoring_hints": ["Cairo-Bishop診断基準"],
        "urgency_override": "immediate",
    },
    {
        "id": "SVC_SYNDROME",
        "keywords": ["上大静脈", "顔面浮腫", "腕の浮腫", "頸静脈怒張", "縦隔", "SVC"],
        "diagnoses": [
            {"disease": "上大静脈症候群（SVCS）", "icd10": "I87.1", "base_prob": 0.72,
             "boost_kw": ["縦隔腫瘍", "肺がん", "リンパ腫", "顔面浮腫", "頸静脈怒張", "側副血行路"]},
            {"disease": "縦隔腫瘍（リンパ腫）", "icd10": "C85.9", "base_prob": 0.12,
             "boost_kw": ["縦隔", "リンパ節腫大", "LDH上昇", "リンパ腫"]},
            {"disease": "肺がん（縦隔浸潤）", "icd10": "C34.9", "base_prob": 0.10,
             "boost_kw": ["肺がん", "喫煙歴", "小細胞肺がん", "NSCLC"]},
            {"disease": "中心静脈カテーテル血栓", "icd10": "T82.8", "base_prob": 0.06,
             "boost_kw": ["CVC", "カテーテル", "血栓"]},
        ],
        "red_flags": ["気道圧迫・意識障害は超緊急→ステロイド即投与", "確定診断前に組織採取を試みる（治療方針に直結）"],
        "next_steps": ["造影CT胸部（縦隔評価）", "デキサメタゾン（緊急症状時）", "腫瘍生検（可能であれば）", "放射線科・腫瘍科コンサルト"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    {
        "id": "HYPERCALCEMIA",
        "keywords": ["高カルシウム", "倦怠感", "嘔気", "意識障害", "悪性", "PTHrP"],
        "diagnoses": [
            {"disease": "悪性高カルシウム血症", "icd10": "E83.5", "base_prob": 0.65,
             "boost_kw": ["悪性腫瘍", "PTHrP", "骨転移", "倦怠感", "意識障害", "嘔気"]},
            {"disease": "原発性副甲状腺機能亢進症", "icd10": "E21.0", "base_prob": 0.20,
             "boost_kw": ["PTH高値", "腎結石", "骨粗鬆症", "無症状"]},
            {"disease": "VitD中毒・VitD産生腫瘍", "icd10": "E55.9", "base_prob": 0.08,
             "boost_kw": ["VitD", "リンパ腫", "サルコイドーシス", "1,25VitD上昇"]},
            {"disease": "サルコイドーシス", "icd10": "D86.9", "base_prob": 0.07,
             "boost_kw": ["肺門リンパ節腫大", "ACE上昇", "肉芽腫"]},
        ],
        "red_flags": ["補正Ca>14mg/dL→生理食塩水急速輸液", "意識障害はCa値確認必須", "ビスホスホネート（ゾレドロン酸）は効果発現2〜4日"],
        "next_steps": ["補正Ca算出（実測Ca+0.8×(4-Alb)）", "生食輸液2〜4L/日", "ゾレドロン酸4mg点滴", "PTH・PTHrP測定", "悪性腫瘍スクリーニング"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    {
        "id": "RA_CRISIS",
        "keywords": ["関節リウマチ", "関節炎", "RF陽性", "抗CCP", "朝のこわばり", "多関節"],
        "diagnoses": [
            {"disease": "関節リウマチ（RA）", "icd10": "M05.9", "base_prob": 0.65,
             "boost_kw": ["朝のこわばり", "RF陽性", "抗CCP抗体", "対称性関節炎", "手指", "MCP", "PIP"]},
            {"disease": "全身性エリテマトーデス（SLE）", "icd10": "M32.9", "base_prob": 0.12,
             "boost_kw": ["ANA陽性", "蝶形紅斑", "若年女性", "光線過敏", "抗dsDNA"]},
            {"disease": "乾癬性関節炎", "icd10": "M07.3", "base_prob": 0.10,
             "boost_kw": ["皮疹", "爪変化", "RF陰性", "脊椎"]},
            {"disease": "反応性関節炎", "icd10": "M02.9", "base_prob": 0.08,
             "boost_kw": ["感染後", "尿道炎", "結膜炎", "HLA-B27"]},
            {"disease": "痛風・偽痛風", "icd10": "M10.9", "base_prob": 0.05,
             "boost_kw": ["高尿酸血症", "単関節", "母趾", "急性発作"]},
        ],
        "red_flags": ["RA肺合併症（間質性肺炎）のスクリーニング", "感染症除外後にステロイド使用判断", "生物学的製剤投与前にTB・B型肝炎スクリーニング"],
        "next_steps": ["RF・抗CCP抗体・ANA", "CRP・ESR・CBC", "関節X線（両手・足）", "リウマチ科コンサルト", "DAS28評価"],
        "scoring_hints": ["DAS28スコア", "ACR/EULAR 2010年分類基準"],
        "urgency_override": None,
    },
]

# メインリストに追加
EXTENDED_DD_RULES.extend(SUPPLEMENT_RULES)

# ── ベンチマーク強化ルール (v3) ─────────────────────────────────
BENCHMARK_RULES = [
    # 急性虫垂炎の非典型キーワード強化
    {
        "id": "APPENDICITIS_V2",
        "min_match": 1,
        "keywords": ["右側腹部痛", "食欲低下", "腹部圧痛", "臍周囲痛", "Alvarado"],
        "diagnoses": [
            {"disease": "急性虫垂炎", "icd10": "K37", "base_prob": 0.68,
             "boost_kw": ["右側腹部","発熱","WBC","CRP","超音波"]},
            {"disease": "腸管膜リンパ節炎", "icd10": "I88.0", "base_prob": 0.15,
             "boost_kw": ["上気道炎","若年","軽症"]},
            {"disease": "卵巣疾患", "icd10": "N83.9", "base_prob": 0.12,
             "boost_kw": ["女性","骨盤痛","月経"]},
            {"disease": "大腸憩室炎", "icd10": "K57.3", "base_prob": 0.05,
             "boost_kw": ["高齢","左下腹部","既往"]},
        ],
        "red_flags": ["女性は必ずβ-hCG確認", "穿孔→汎発性腹膜炎"],
        "next_steps": ["腹部CT", "採血(WBC/CRP)", "外科コンサルト"],
        "scoring_hints": ["Alvarado score"],
        "urgency_override": None,
    },
    # 非典型ACS (上腹部痛・歯痛など)
    {
        "id": "ATYPICAL_ACS",
        "min_match": 1,
        "keywords": ["上腹部不快感", "食後胸部", "歯痛", "げっぷ", "胸部不快感", "糖尿病 高血圧 喫煙"],
        "diagnoses": [
            {"disease": "急性冠症候群（非典型）", "icd10": "I21.9", "base_prob": 0.55,
             "boost_kw": ["糖尿病","高血圧","喫煙","高齢","男性","TnI"]},
            {"disease": "胃食道逆流症（GERD）", "icd10": "K21.0", "base_prob": 0.20,
             "boost_kw": ["食後増悪","臥位増悪","PPI有効"]},
            {"disease": "急性胃炎", "icd10": "K29.0", "base_prob": 0.15,
             "boost_kw": ["NSAIDs","アルコール","嘔気"]},
            {"disease": "胆嚢炎", "icd10": "K81.0", "base_prob": 0.10,
             "boost_kw": ["脂肪食後","右季肋部","Murphy"]},
        ],
        "red_flags": ["糖尿病+高血圧+喫煙の危険因子がある場合は必ず12誘導心電図"],
        "next_steps": ["12誘導心電図(必須)", "TnI採血", "腹部超音波"],
        "scoring_hints": ["HEART score"],
        "urgency_override": None,
    },
    # 粘液水腫性昏睡
    {
        "id": "MYXEDEMA_COMA",
        "min_match": 1,
        "keywords": ["粘液水腫", "甲状腺機能低下", "低体温", "徐脈", "意識混濁 甲状腺", "T4低下"],
        "diagnoses": [
            {"disease": "粘液水腫性昏睡", "icd10": "E03.5", "base_prob": 0.78,
             "boost_kw": ["低体温","徐脈","甲状腺加療中断","TSH上昇","甲状腺機能低下"]},
            {"disease": "敗血症性ショック", "icd10": "A41.9", "base_prob": 0.12,
             "boost_kw": ["発熱","感染源","CRP","WBC"]},
            {"disease": "副腎クリーゼ", "icd10": "E27.2", "base_prob": 0.10,
             "boost_kw": ["ステロイド中断","低Na","副腎"]},
        ],
        "red_flags": ["体温35℃以下→重篤", "即刻甲状腺ホルモン補充(T4/T3 IV)"],
        "next_steps": ["甲状腺機能(FT4/TSH)", "甲状腺ホルモン静注", "保温・ICU管理"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    # 褐色細胞腫
    {
        "id": "PHEOCHROMOCYTOMA",
        "min_match": 1,
        "keywords": ["発作性高血圧", "カテコラミン", "褐色細胞腫", "発汗 動悸 頭痛", "副腎腫瘤"],
        "diagnoses": [
            {"disease": "褐色細胞腫", "icd10": "D35.0", "base_prob": 0.68,
             "boost_kw": ["発作性高血圧","発汗","動悸","頭痛","三徴","副腎"]},
            {"disease": "本態性高血圧", "icd10": "I10", "base_prob": 0.15,
             "boost_kw": ["持続性","家族歴"]},
            {"disease": "甲状腺クリーゼ", "icd10": "E05.5", "base_prob": 0.10,
             "boost_kw": ["甲状腺","高熱","意識障害"]},
            {"disease": "パニック発作", "icd10": "F41.0", "base_prob": 0.07,
             "boost_kw": ["精神的ストレス","過換気","血圧正常化"]},
        ],
        "red_flags": ["α遮断薬なしにβ遮断薬を使用禁止(高血圧悪化)", "カテコラミン尿測定"],
        "next_steps": ["24h尿中カテコラミン/VMA/メタネフリン", "腹部MRI/CT", "内分泌コンサルト"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    # 腸閉塞
    {
        "id": "BOWEL_OBSTRUCTION",
        "min_match": 1,
        "keywords": ["排ガス停止", "腸閉塞", "腸管閉塞", "腹部膨満 嘔吐", "開腹手術歴 腹痛"],
        "diagnoses": [
            {"disease": "腸閉塞（イレウス）", "icd10": "K56.6", "base_prob": 0.72,
             "boost_kw": ["排ガス停止","腹部膨満","嘔吐","手術歴","腸管拡張"]},
            {"disease": "大腸癌による閉塞", "icd10": "C18.9", "base_prob": 0.15,
             "boost_kw": ["高齢","血便","体重減少","腫瘤"]},
            {"disease": "腸管虚血（SMA閉塞）", "icd10": "K55.0", "base_prob": 0.08,
             "boost_kw": ["心房細動","突然","激痛","不釣合い"]},
            {"disease": "急性偽性腸閉塞（Ogilvie）", "icd10": "K59.3", "base_prob": 0.05,
             "boost_kw": ["術後","ICU","電解質"]},
        ],
        "red_flags": ["腸管壊死→穿孔リスク", "腸管虚血は pain out of proportion に注意"],
        "next_steps": ["腹部X線(ニボー像)", "腹部CT(造影)", "禁食+輸液", "外科コンサルト"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    # 2型糖尿病（初発・症状あり）
    {
        "id": "DM_TYPE2",
        "min_match": 1,
        "keywords": ["多飲多尿", "体重減少 倦怠感", "高血糖", "HbA1c", "視力低下 糖尿", "口渇"],
        "diagnoses": [
            {"disease": "2型糖尿病（初発）", "icd10": "E11.9", "base_prob": 0.70,
             "boost_kw": ["多飲多尿","体重減少","高血糖","HbA1c","肥満","家族歴"]},
            {"disease": "1型糖尿病", "icd10": "E10.9", "base_prob": 0.15,
             "boost_kw": ["若年","急激発症","痩せ型","ケトーシス"]},
            {"disease": "薬剤性高血糖", "icd10": "E16.0", "base_prob": 0.10,
             "boost_kw": ["ステロイド","抗精神病薬"]},
            {"disease": "二次性糖尿病", "icd10": "E13", "base_prob": 0.05,
             "boost_kw": ["膵疾患","クッシング","先端巨大症"]},
        ],
        "red_flags": ["HbA1c≥10%→急性期合併症リスク高", "眼底・腎機能・足の初回評価必須"],
        "next_steps": ["空腹時血糖+HbA1c", "尿検査(蛋白/ケトン)", "眼底検査", "腎機能"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    # ギラン・バレー症候群
    {
        "id": "GBS",
        "min_match": 1,
        "keywords": ["ギラン", "GBS", "上行性麻痺", "深部腱反射消失", "四肢麻痺 感覚障害", "先行感染 麻痺"],
        "diagnoses": [
            {"disease": "ギラン・バレー症候群（GBS）", "icd10": "G61.0", "base_prob": 0.75,
             "boost_kw": ["上行性麻痺","腱反射消失","先行感染","アルブミン細胞解離","IVIG"]},
            {"disease": "多発性硬化症（MS）", "icd10": "G35", "base_prob": 0.12,
             "boost_kw": ["若年女性","再発寛解","MRI白質病変","視力障害"]},
            {"disease": "脊髄炎", "icd10": "G37.3", "base_prob": 0.08,
             "boost_kw": ["腱反射亢進","Babinski","脊髄MRI"]},
            {"disease": "筋無力症（MG）", "icd10": "G70.0", "base_prob": 0.05,
             "boost_kw": ["眼瞼下垂","易疲労","夕方増悪","AChR抗体"]},
        ],
        "red_flags": ["呼吸筋麻痺→換気補助の準備", "自律神経障害→心拍変動モニタリング"],
        "next_steps": ["腰椎穿刺(アルブミン細胞解離)", "神経伝導検査", "IVIG/血漿交換", "呼吸機能評価"],
        "scoring_hints": [],
        "urgency_override": "urgent",
    },
    # 急性心膜炎（独立ルール）
    {
        "id": "PERICARDITIS",
        "min_match": 1,
        "keywords": ["心膜炎", "前傾位", "胸膜性胸痛", "心膜摩擦音", "ST上昇 PR低下", "鞍型"],
        "diagnoses": [
            {"disease": "急性心膜炎", "icd10": "I30.9", "base_prob": 0.72,
             "boost_kw": ["前傾位で軽減","摩擦音","PR低下","鞍型ST上昇","ウイルス"]},
            {"disease": "急性冠症候群（ACS）", "icd10": "I21.9", "base_prob": 0.15,
             "boost_kw": ["危険因子","ST上昇局在","TnI著明上昇"]},
            {"disease": "心タンポナーデ", "icd10": "I31.9", "base_prob": 0.08,
             "boost_kw": ["Beck三徴","頸静脈怒張","心音減弱","奇脈"]},
            {"disease": "大動脈解離", "icd10": "I71.0", "base_prob": 0.05,
             "boost_kw": ["引き裂く","血圧左右差"]},
        ],
        "red_flags": ["高熱+炎症マーカー著高→細菌性心膜炎除外", "心タンポナーデ移行に注意"],
        "next_steps": ["心電図(PR低下/鞍型ST確認)", "心エコー(心嚢液)", "NSAIDs+コルヒチン"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    # 甲状腺機能低下症（慢性）
    {
        "id": "HYPOTHYROIDISM",
        "min_match": 1,
        "keywords": ["甲状腺機能低下", "倦怠感 体重増加", "寒がり", "TSH上昇", "便秘 浮腫 低体温"],
        "diagnoses": [
            {"disease": "甲状腺機能低下症（橋本病）", "icd10": "E03.9", "base_prob": 0.72,
             "boost_kw": ["倦怠感","体重増加","寒がり","便秘","TSH上昇","FT4低下","橋本"]},
            {"disease": "うつ病", "icd10": "F32.9", "base_prob": 0.15,
             "boost_kw": ["気分低下","不眠","興味喪失","若年","女性"]},
            {"disease": "貧血", "icd10": "D64.9", "base_prob": 0.08,
             "boost_kw": ["Hb低下","鉄欠乏","月経過多"]},
            {"disease": "心不全", "icd10": "I50.9", "base_prob": 0.05,
             "boost_kw": ["浮腫","BNP高値","心拡大"]},
        ],
        "red_flags": ["急激な発症+低体温+意識障害→粘液水腫性昏睡"],
        "next_steps": ["TSH+FT4", "抗TPO抗体", "L-チロキシン補充療法", "甲状腺エコー"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    # 多発性硬化症
    {
        "id": "MULTIPLE_SCLEROSIS",
        "min_match": 1,
        "keywords": ["多発性硬化症", "MS", "視神経炎", "時間的多発", "空間的多発", "再発寛解", "白質病変"],
        "diagnoses": [
            {"disease": "多発性硬化症（MS）", "icd10": "G35", "base_prob": 0.68,
             "boost_kw": ["若年女性","視神経炎","再発寛解","MRI白質病変","Lhermitte徴候"]},
            {"disease": "視神経脊髄炎（NMOSD）", "icd10": "G36.0", "base_prob": 0.15,
             "boost_kw": ["視神経炎","横断性脊髄炎","AQP4抗体"]},
            {"disease": "中枢神経SLE", "icd10": "M32.1", "base_prob": 0.10,
             "boost_kw": ["SLE","ANA","補体低下","皮疹"]},
            {"disease": "脳腫瘍", "icd10": "C71.9", "base_prob": 0.07,
             "boost_kw": ["進行性","頭蓋内圧亢進","頭痛"]},
        ],
        "red_flags": ["視神経炎→眼科緊急", "脊髄炎→MRI緊急"],
        "next_steps": ["頭部MRI(造影)", "髄液検査(オリゴクローナルバンド)", "視覚誘発電位", "神経内科コンサルト"],
        "scoring_hints": ["McDonald基準2017"],
        "urgency_override": None,
    },
    # 川崎病
    {
        "id": "KAWASAKI",
        "min_match": 1,
        "keywords": ["川崎病", "Kawasaki", "イチゴ舌", "眼球結膜充血 発熱 小児", "冠動脈瘤 小児"],
        "diagnoses": [
            {"disease": "川崎病", "icd10": "M30.3", "base_prob": 0.80,
             "boost_kw": ["5日以上発熱","眼球充血","口唇発赤","イチゴ舌","手足浮腫","体幹発疹","小児"]},
            {"disease": "猩紅熱", "icd10": "A38", "base_prob": 0.10,
             "boost_kw": ["A群溶連菌","砂紙様発疹","咽頭炎"]},
            {"disease": "スティル病（全身型JIA）", "icd10": "M08.2", "base_prob": 0.06,
             "boost_kw": ["サーモン色発疹","関節炎","リウマトイド因子陰性"]},
            {"disease": "ウイルス性発疹症", "icd10": "B09", "base_prob": 0.04,
             "boost_kw": ["発疹","軽症","自然消失"]},
        ],
        "red_flags": ["冠動脈瘤→心エコー必須", "発熱5日以上→川崎病精査"],
        "next_steps": ["心エコー(冠動脈評価)", "採血(WBC/CRP/ESR/BNP)", "IVIG 2g/kg", "アスピリン"],
        "scoring_hints": [],
        "urgency_override": "urgent",
    },
    # ARDS
    {
        "id": "ARDS",
        "min_match": 1,
        "keywords": ["ARDS", "急性呼吸窮迫", "両側浸潤影 呼吸不全", "P/F比低下", "PaO2/FiO2"],
        "diagnoses": [
            {"disease": "急性呼吸窮迫症候群（ARDS）", "icd10": "J80", "base_prob": 0.72,
             "boost_kw": ["P/F比<300","両側浸潤","肺水腫","先行原因","PEEP"]},
            {"disease": "重症肺炎（CAP）", "icd10": "J18.9", "base_prob": 0.15,
             "boost_kw": ["肺炎球菌","片側浸潤","抗菌薬有効"]},
            {"disease": "心原性肺水腫", "icd10": "J81", "base_prob": 0.10,
             "boost_kw": ["BNP高値","楔入圧上昇","利尿薬有効"]},
            {"disease": "肺出血", "icd10": "R04.2", "base_prob": 0.03,
             "boost_kw": ["血痰","抗GBM抗体","Goodpasture"]},
        ],
        "red_flags": ["P/F<150→ICU挿管", "Berlin分類でARDS確定"],
        "next_steps": ["ICU管理", "肺保護換気(TV 6mL/kg)", "腹臥位換気", "原因治療"],
        "scoring_hints": ["Berlin criteria (mild/moderate/severe)"],
        "urgency_override": "immediate",
    },
    # 播種性血管内凝固 (DIC)
    {
        "id": "DIC",
        "min_match": 1,
        "keywords": ["DIC", "播種性血管内凝固", "血小板減少 PT延長", "フィブリン分解産物", "多臓器不全 出血"],
        "diagnoses": [
            {"disease": "播種性血管内凝固（DIC）", "icd10": "D65", "base_prob": 0.78,
             "boost_kw": ["血小板減少","PT/APTT延長","Ddimer上昇","フィブリノゲン低下","出血"]},
            {"disease": "血栓性血小板減少性紫斑病（TTP）", "icd10": "M31.1", "base_prob": 0.10,
             "boost_kw": ["溶血性貧血","血小板減少","腎不全","神経症状","発熱"]},
            {"disease": "HUS（溶血性尿毒症）", "icd10": "D59.3", "base_prob": 0.07,
             "boost_kw": ["STEC感染","下痢","小児","TMA"]},
            {"disease": "重症肝不全", "icd10": "K72.0", "base_prob": 0.05,
             "boost_kw": ["肝炎","肝硬変","PT延長のみ"]},
        ],
        "red_flags": ["出血+血栓の並存がDICの特徴", "基礎疾患（敗血症/悪性腫瘍）の治療が最優先"],
        "next_steps": ["PT/APTT/フィブリノゲン/Ddimer/血小板", "基礎疾患治療", "新鮮凍結血漿/血小板輸血"],
        "scoring_hints": ["JAAM DICスコア≥4"],
        "urgency_override": "immediate",
    },
    # 肝性脳症
    {
        "id": "HEPATIC_ENCEPHALOPATHY",
        "min_match": 1,
        "keywords": ["肝性脳症", "肝硬変 意識障害", "アンモニア高値", "flapping tremor", "肝不全 意識"],
        "diagnoses": [
            {"disease": "肝性脳症", "icd10": "K72.9", "base_prob": 0.72,
             "boost_kw": ["肝硬変","アンモニア","フラッピング","意識障害","誘因"]},
            {"disease": "低血糖性昏睡", "icd10": "E16.0", "base_prob": 0.12,
             "boost_kw": ["糖尿病","インスリン","血糖測定"]},
            {"disease": "ウェルニッケ脳症", "icd10": "E51.2", "base_prob": 0.10,
             "boost_kw": ["アルコール","眼球運動障害","運動失調","チアミン"]},
            {"disease": "敗血症性脳症", "icd10": "A41.9", "base_prob": 0.06,
             "boost_kw": ["感染源","発熱","CRP上昇"]},
        ],
        "red_flags": ["誘因の同定と除去が最優先", "気道保護（嘔吐・誤嚥リスク）"],
        "next_steps": ["血中アンモニア", "血糖測定", "ラクツロース投与", "誘因（GI出血/感染/脱水）除去"],
        "scoring_hints": ["West Haven分類 Grade 0-4"],
        "urgency_override": "urgent",
    },
    # 悪性症候群 (NMS)
    {
        "id": "NMS",
        "min_match": 1,
        "keywords": ["悪性症候群", "NMS", "抗精神病薬 高熱", "筋強剛 発汗", "CK著明上昇"],
        "diagnoses": [
            {"disease": "悪性症候群（NMS）", "icd10": "G21.0", "base_prob": 0.75,
             "boost_kw": ["抗精神病薬","高熱","筋強剛","意識障害","CK上昇","発汗"]},
            {"disease": "セロトニン症候群", "icd10": "T43.2", "base_prob": 0.15,
             "boost_kw": ["SSRI","抗うつ薬","振戦","間代性クローヌス","急性発症"]},
            {"disease": "悪性高熱症（MH）", "icd10": "T88.3", "base_prob": 0.07,
             "boost_kw": ["吸入麻酔","筋弛緩薬","術中","ダントロレン"]},
            {"disease": "熱中症", "icd10": "T67.0", "base_prob": 0.03,
             "boost_kw": ["高温環境","労作","冷却"]},
        ],
        "red_flags": ["原因薬剤を即中止", "ダントロレン静注", "積極的冷却"],
        "next_steps": ["原因薬剤中止", "CK/腎機能モニタリング", "ダントロレン", "補液・冷却"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    # 急性緑内障発作
    {
        "id": "ACUTE_GLAUCOMA",
        "min_match": 1,
        "keywords": ["緑内障", "眼圧上昇", "眼痛 頭痛 嘔吐", "霧視", "散瞳 眼痛"],
        "diagnoses": [
            {"disease": "急性閉塞隅角緑内障", "icd10": "H40.0", "base_prob": 0.78,
             "boost_kw": ["眼痛","眼圧上昇","散瞳","霧視","頭痛","嘔吐","暗い場所"]},
            {"disease": "急性結膜炎", "icd10": "H10.9", "base_prob": 0.10,
             "boost_kw": ["充血","分泌物","両眼","軽症"]},
            {"disease": "虹彩炎（前部ぶどう膜炎）", "icd10": "H20.0", "base_prob": 0.08,
             "boost_kw": ["縮瞳","羞明","角膜後面沈着物","関節炎"]},
            {"disease": "片頭痛", "icd10": "G43.9", "base_prob": 0.04,
             "boost_kw": ["視覚前兆","一側性","既往"]},
        ],
        "red_flags": ["眼圧>40mmHg→失明リスク", "眼科緊急コール（数時間以内の治療が必要）"],
        "next_steps": ["眼科緊急コール", "眼圧測定", "アセタゾラミド静注", "縮瞳薬点眼"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    # 大動脈瘤破裂（改善版）
    {
        "id": "AORTIC_ANEURYSM_RUPTURE",
        "min_match": 1,
        "keywords": ["大動脈瘤破裂", "腹部拍動性腫瘤 ショック", "突然の腹背部痛 ショック"],
        "diagnoses": [
            {"disease": "腹部大動脈瘤破裂", "icd10": "I71.3", "base_prob": 0.82,
             "boost_kw": ["ショック","腹部拍動性腫瘤","突然","高齢男性","喫煙"]},
            {"disease": "急性大動脈解離（B型）", "icd10": "I71.0", "base_prob": 0.12,
             "boost_kw": ["引き裂く","高血圧","血圧左右差"]},
            {"disease": "上腸管膜動脈閉塞", "icd10": "K55.0", "base_prob": 0.06,
             "boost_kw": ["心房細動","腸管虚血","急性腹症"]},
        ],
        "red_flags": ["即刻外科緊急コール", "造影CT(安定例のみ)", "不安定例は直接手術室"],
        "next_steps": ["大口径静脈路2本確保", "血型・交差試験", "外科緊急コール", "CT(血圧安定時)"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
    # 腎性尿細管アシドーシス（多発性嚢胞腎など）
    {
        "id": "PKD",
        "min_match": 1,
        "keywords": ["多発性嚢胞腎", "PKD", "嚢胞腎", "両側腎腫大", "血尿 腰背部痛 高血圧 家族歴"],
        "diagnoses": [
            {"disease": "常染色体優性多発性嚢胞腎（ADPKD）", "icd10": "Q61.2", "base_prob": 0.72,
             "boost_kw": ["家族歴","両側腎腫大","高血圧","腎機能低下","超音波嚢胞"]},
            {"disease": "単純性腎嚢胞", "icd10": "N28.1", "base_prob": 0.15,
             "boost_kw": ["単発","偶発発見","無症状"]},
            {"disease": "腎癌", "icd10": "C64", "base_prob": 0.10,
             "boost_kw": ["血尿","腫瘤","体重減少"]},
            {"disease": "慢性腎臓病（CKD）", "icd10": "N18.9", "base_prob": 0.03,
             "boost_kw": ["Cr上昇","蛋白尿","腎機能低下"]},
        ],
        "red_flags": ["くも膜下出血リスク（脳動脈瘤の合併）", "高血圧の厳格管理（BP<130/80）"],
        "next_steps": ["腎超音波/MRI", "遺伝子検査(PKD1/PKD2)", "降圧療法", "遺伝カウンセリング"],
        "scoring_hints": [],
        "urgency_override": None,
    },
]

# メインリストに追加
EXTENDED_DD_RULES.extend(BENCHMARK_RULES)

# ── Hard ケース用追加ルール ───────────────────────────────────
HARD_RULES = [
    {
        "id": "MALIGNANT_LYMPHOMA",
        "min_match": 1,
        "keywords": ["悪性リンパ腫", "不明熱", "リンパ節腫脹 発熱", "B症状", "夜間発汗 体重減少"],
        "diagnoses": [
            {"disease": "悪性リンパ腫", "icd10": "C85.9", "base_prob": 0.55,
             "boost_kw": ["B症状","リンパ節腫脹","LDH上昇","夜間発汗","体重減少"]},
            {"disease": "固形腫瘍（転移）", "icd10": "C80.1", "base_prob": 0.15,
             "boost_kw": ["既往癌","転移","腫瘍マーカー"]},
            {"disease": "結核", "icd10": "A15.9", "base_prob": 0.15,
             "boost_kw": ["渡航歴","IGRA","上葉"]},
            {"disease": "HIV感染症", "icd10": "B24", "base_prob": 0.10,
             "boost_kw": ["リスク行動","CD4","日和見"]},
            {"disease": "Still病（成人型）", "icd10": "M06.1", "base_prob": 0.05,
             "boost_kw": ["サーモン色発疹","フェリチン著高","関節炎"]},
        ],
        "red_flags": ["3週間以上の不明熱は悪性腫瘍を積極的に除外", "骨髄生検"],
        "next_steps": ["PET-CT", "リンパ節生検", "骨髄生検", "LDH/β2-MG/フェリチン"],
        "scoring_hints": [],
        "urgency_override": None,
    },
    {
        "id": "BOTULISM",
        "min_match": 1,
        "keywords": ["ボツリヌス", "下降性麻痺", "嚥下障害 呼吸困難 複視", "食物中毒 麻痺"],
        "diagnoses": [
            {"disease": "ボツリヌス症", "icd10": "A05.1", "base_prob": 0.65,
             "boost_kw": ["下降性麻痺","嚥下障害","複視","呼吸困難","自律神経","食物中毒"]},
            {"disease": "ギラン・バレー症候群", "icd10": "G61.0", "base_prob": 0.20,
             "boost_kw": ["反射消失","先行感染","アルブミン細胞解離","上行性"]},
            {"disease": "重症筋無力症", "icd10": "G70.0", "base_prob": 0.10,
             "boost_kw": ["夕方増悪","眼瞼下垂","AChR抗体","テンシロン"]},
            {"disease": "有機リン中毒", "icd10": "T60.0", "base_prob": 0.05,
             "boost_kw": ["農薬","SLUDGE","縮瞳","アトロピン"]},
        ],
        "red_flags": ["呼吸筋麻痺→換気補助の準備", "集団食中毒の可能性→届出"],
        "next_steps": ["ボツリヌス毒素検査（便・血清）", "換気補助準備", "抗毒素血清", "感染症科コンサルト"],
        "scoring_hints": [],
        "urgency_override": "immediate",
    },
]

EXTENDED_DD_RULES.extend(HARD_RULES)
